### ISSUE TITLE
Combine jobs if number of jobs will exceed submit limit

### ISSUE THREAD

**Issue by forsyth2** [E3SM-Project/zppy#102]
Some machines place a limit on the number of jobs a user can submit at a time. This limit is usually high enough to not cause concern (e.g., https://docs.nersc.gov/jobs/policy/ -- 5000 jobs can be submitted). However, if the limit is reached, than the jobs won't be submitted. In that case, it may be useful for `zppy` to combine batch jobs into larger jobs so that fewer jobs are submitted to the queue.

**Comment by sarats** [comment]
Are you talking about jobs for model diagnostics here or multiple model runs?

**Comment by forsyth2** [comment]
> Are you talking about jobs for model diagnostics here or multiple model runs?

Jobs for model diagnostics. `zppy` doesn't actually run the model.

**Comment by forsyth2** [comment]
#243 added the ability to bundle jobs. It is not automatic (i.e., `zppy` doesn't determine for itself the number of jobs it should run), but it is arguably better for users themselves to decide how to bundle their jobs. So, closing.
