### ISSUE TITLE
Add annual_cycle_zonal_mean set to e3sm_diags default

### ISSUE THREAD

**Issue by tangq** [E3SM-Project/zppy#110]
e3sm_diags recently added a new set of plots called "annual_cycle_zonal_mean". This is particularly important for checking the stratospheric ozone performance.

Can we add it to the default? We will need a 1-line change in default.ini: `sets = string_list(default=list("lat_lon","zonal_mean_xy","zonal_mean_2d","polar","cosp_histogram","meridional_mean_2d","annual_cycle_zonal_mean"))`

**Comment by forsyth2** [comment]
@tangq Isn't this what #108 did?
