### ISSUE TITLE
calculate climo files on history tapes other than h0

### ISSUE THREAD

**Issue by tangq** [E3SM-Project/zppy#116]
The atmospheric budget diagnostics require climo files on monthly instantaneous output (currently uses the h1 files). We need to change the climo.bash template to allow input files other than h0 by adding lines below:
```
{% elif frequency == 'monthly_inst' %}

ncclimo \
--case={{ case }} \
{%- if exclude %}
-n '-x' \
{%- endif %}
{%- if vars != '' %}
--vars={{ vars }} \
{%- endif %}
--parallel=mpi \
--december_mode=sdd \
--mdl_nm=eam \
--hst_nm=h1 \
--fml_nm={{ case }}.h1 \
--yr_srt={{ yr_start }} \
--yr_end={{ yr_end }} \
--input={{ input }}/{{ input_subdir }} \
{% if mapping_file == '' -%}
--output=output \
{%- else -%}
--map={{ mapping_file }} \
--output=trash \
--regrid=output \
{%- endif %}
```

**Comment by golaz** [comment]
@tangq : I think we can implement something along these lines, but I'd like to have a more generic implementation to avoid having too many special cases.

I wonder if we could replace

https://github.com/E3SM-Project/zppy/blob/ff980c6c0d707e9d2b339a11506c36ef06c055a7/zppy/templates/climo.bash#L25

with an if for "monthly" or "monthly_inst" and add the flexibility to use different h* input files, something like

--history={{ input_files.split(".")[1] }}

(--history appears to be the same as --hst_nm, but less obscure).

Need input from @forsyth2.

**Comment by tangq** [comment]
@golaz , I found it's more flexible to handle this in the "ts" section, because for my application the time series data is better than the climos. But it's still useful to have a more flexible climo options.

**Comment by golaz** [comment]
Sounds like this is no longer needed if using "ts" is better for what you want to do. Let's close this for now until there is a need.
