### ISSUE TITLE
Print all settings in each generated script

### ISSUE THREAD

**Issue by golaz** [E3SM-Project/zppy#121]
Due to the inheritance model and default settings, it can sometimes be difficult to know exactly what settings were passed when instantiating a specific Jinja2 template.

To help debugging, it would be useful to print all the settings near the top of the job itself (as comments).

Not sure how easy it is to do:

https://stackoverflow.com/questions/27805445/print-all-jinja2-variables-in-a-template
https://stackoverflow.com/questions/3398850/how-to-get-a-list-of-current-variables-from-jinja-2-template

**Comment by golaz** [comment]
@forsyth2 : do you think we could incorporate this into the intermediate release for E3SM Unified 1.5.1? This would be purely diagnostics, but would help users figure out what is going on (when needed). Could be especially after adding the campaign option: https://github.com/E3SM-Project/zppy/pull/135

**Comment by forsyth2** [comment]
@golaz I'll take a look and see how easily we could implement it. I agree it would be very useful to have.

**Comment by forsyth2** [comment]
@golaz It looks like adding `print("task: {}, year_set: {}".format(c, s))` in `zppy/e3sm_diags.py` is sufficient to print the settings when `zppy` is run. I could try to pretty-print the output, redirect it to a file, and do so for each of the `zppy/*.py` files. Would that be good?
