### ISSUE TITLE
Add parameter to specify science campaign

### ISSUE THREAD

**Issue by forsyth2** [E3SM-Project/zppy#122]
Add parameter to specify science campaign. For example: if `campaign = "water_cycle"` then set E3SM Diags `sets` to include particular sets.

**Comment by forsyth2** [comment]
@xylar @wlin7 FYI

**Comment by xylar** [comment]
@forsyth2, excellent! Once this parameter is added, I will be happy to make a PR that adds support for `campaign = "cryosphere"` and get @wlin7 to help with the `e3sm_diags` configuration.

**Comment by forsyth2** [comment]
Closed by #138
