### ISSUE TITLE
Single script execution mode?

### ISSUE THREAD

**Issue by golaz** [E3SM-Project/zppy#123]
As @PeterCaldwell rightly pointed out, zppy submitting 10's to 100's of batch jobs could be problematic on some machines with restrictions on the number of jobs that one user can submit (or run) and that don't have a dedicated post-processing cluster attached to the same file system.

A possible workaround would be to implement a **single script execution mode**. Instead of zppy submitting each job individually, they would all be bundled up into a single master script (in proper order to satisfy dependencies).

We could consider implementing such a feature if this becomes a real limitation on one of our E3SM platform.

Tagging @forsyth2, @chengzhuzhang, @sarats

**Comment by forsyth2** [comment]
This is more or less the intention of #102.

**Comment by tangq** [comment]
Since MPAS-Analysis can take a long time to run, it is better to separate it from the bundled job.

**Comment by PeterCaldwell** [comment]
I just asked out of curiosity. I don't think we should put energy into solving - or even scoping the problem via this git issue - until we have a real-world case requiring us to do so...

**Comment by golaz** [comment]
Closing. This will be implemented as part of https://github.com/E3SM-Project/zppy/issues/189.
