### ISSUE TITLE
Move `e3sm_diags_vs_model` functionality into `e3sm_diags` task

### ISSUE THREAD

**Issue by forsyth2** [E3SM-Project/zppy#147]
Move `e3sm_diags_vs_model` functionality into the `e3sm_diags` task. That is, model-vs-model comparison should be done as a subtask of `e3sm_diags` rather than as its own task.

**Comment by wlin7** [comment]
@forsyth2 , sound good for streamlining the tasks. Will we have the option to turn either one (vs_obs or vs_model) off? There will be scenarios we only want to run one of them.

**Comment by forsyth2** [comment]
@wlin7 I haven't thought too much about this yet, but yes that sounds like a good idea. The general plan is to use subtasks, so we could have something like the following in the configuration file:

```
[e3sm_diags]
...

  [[ atm_monthly_180x360_aave_vs_obs ]]
  type = model_vs_obs
  ...

  [[ atm_monthly_180x360_aave_vs_model ]]
  type = model_vs_model
  ...
```
