### ISSUE TITLE
Add support for BGC campaign

### ISSUE THREAD

**Issue by forsyth2** [E3SM-Project/zppy#151]
Add support for BGC campaign

**Comment by forsyth2** [comment]
For reference, previous campaign pull requests are: #144, #143, #138.

**Comment by forsyth2** [comment]
@chengzhuzhang Do you know what we want to include for the BGC campaign?

Existing campaign files are [water cycle](https://github.com/E3SM-Project/zppy/blob/main/zppy/templates/water_cycle.cfg) and [cryosphere](https://github.com/E3SM-Project/zppy/blob/main/zppy/templates/cryosphere.cfg)

Something like the following?
```
[e3sm_diags]
sets = "lat_lon","zonal_mean_xy","zonal_mean_2d","polar","cosp_histogram","meridional_mean_2d","enso_diags","qbo","diurnal_cycle","annual_cycle_zonal_mean","streamflow","zonal_mean_2d_stratosphere"

[ilamb]
# anything specific to set here?
```

**Comment by chengzhuzhang** [comment]
No, we will need to talk to BGC for coming up a new configuration. I will schedule a meeting.

**Comment by forsyth2** [comment]
@chengzhuzhang Ok, perhaps we can do that as part of the upcoming E3SM Unified / Running E3SM meeting.

**Comment by chengzhuzhang** [comment]
duplicated.

**Comment by forsyth2** [comment]
Duplicated by #385?
