### ISSUE TITLE
Make 'account' for the slurm_header an input option

### ISSUE THREAD

**Issue by milenaveneziani** [E3SM-Project/zppy#157]
It would be nice to be able to choose the `account` name in the `default` section of the config file (basically removing the hard-coded `e3sm` value in `zppy/templates/slurm_header.sh`).

**Comment by xylar** [comment]
@forsyth2, I'm happy to implement this sometime if you don't get a chance.  Seems pretty simple.

**Comment by chengzhuzhang** [comment]
I think this has been implemented, could you confirm? @forsyth2

**Comment by forsyth2** [comment]
Yes, #244 closed #238, which is a duplicate of this issue.
