### ISSUE TITLE
Add zonal mean 2d stratosphere set from e3sm_diags

### ISSUE THREAD

**Issue by chengzhuzhang** [E3SM-Project/zppy#163]
Hey @forsyth2 This is just a heads up that `e3sm_diags` will have a new set in (will be released tomorrow the latest). Adding the new set in zppy will just add one line in configuration file. But timing-wise, it is tricky to coordinate between e3sm_unified and zppy change...

**Comment by forsyth2** [comment]
@chengzhuzhang Should this be included in the default `water_cycle` campaign?  (https://github.com/E3SM-Project/zppy/blob/main/zppy/templates/water_cycle.cfg)

**Comment by chengzhuzhang** [comment]
Yes, absolutely. Since cryo also has zonal_mean_2d, I think add it to cryo as well.

**Comment by forsyth2** [comment]
Sounds good, thanks!
