### ISSUE TITLE
Optimize `ncclimo` calls

### ISSUE THREAD

**Issue by forsyth2** [E3SM-Project/zppy#165]
Optimize `ncclimo` calls.

`zppy/templates/climo.bash` Monthly climatology:
- `--mem_mb=0` is only necessary on Cori, but is ok to use elsewhere. This can be removed after the release of E3SM Unified 1.5.1 (which will include `zppy v1.1.0`). See @czender's comment on #136.
- `--thr=1` is not necessary for low-res. In fact, it hurts low-res performance. @chengzhuzhang and @xylar may consider a hi-res configuration. Related to #9?
- Replace `--model` (`-m`) with `--prc_typ` (`-P`).

`zppy/templates/climo.bash` Diurnal cycle climatology:
- First two bullets above apply here as well.

`zppy/templates/ts.bash`:
- Use `--area` rather than `--area_nm` (same option, just a different name)
- Test with `dpf` and `tpd` removed. Those two options shouldn't be necessary.

Note: to see all `ncclimo` options, just run `ncclimo` with no options.

**Comment by czender** [comment]
I need to add one further comment about this: Replace --model (-m) with --prc_typ (-P). This always works fine for v2 simulations. However, if model is specified as "eam"  (e.g., --prc_typ=eam) then ncclimo will expect the raw filenames to contain "eam". This only became true late in v2 development. If the raw filenames contain "cam" then the model should be specified as "cam", e.g., --prc_typ=cam.

**Comment by chengzhuzhang** [comment]
Mostly resolved in #228 
Can revisit to further optimize later.
