### ISSUE TITLE
global time series doesn't select the correct ocean output

### ISSUE THREAD

**Issue by tangq** [E3SM-Project/zppy#168]
When creating the global time series plot, the script always uses all the output files at the ocn/hist directory to create the ocean time series. This requires the short-term archive was not done for longer time period. Otherwise, the ocean and atmosphere time series won't have the same length and causes failures.

We need to add some code to select the correct ocean input files for the time series matching the atmospheric length.

**Comment by forsyth2** [comment]
Closing in favor of #256.
