### ISSUE TITLE
Fix inheritance in configuration file

### ISSUE THREAD

**Issue by forsyth2** [E3SM-Project/zppy#194]
Specifying `mapping_file = /home/ac.zender/data/maps/map_ne30pg2_to_cmip6_180x360_aave.20200201.nc` under `[default]` results in creating `<output>/post/atm/native` whereas specifying the mapping file under both `[climo]` and `[ts]` results in creating `<output>/post/atm/180x360_aave/`.

It's likely the mapping file specified at https://github.com/E3SM-Project/zppy/blob/main/zppy/templates/default.ini#L20 and https://github.com/E3SM-Project/zppy/blob/main/zppy/templates/default.ini#L44 ends up overriding the value set in `[default]`.

Possible solution: move parameters as high up in the `default.ini` hierarchy as makes sense.

**Comment by golaz** [comment]
@forsyth2 : good catch! Moving the definition of the default value to the `[default]` section should solve the problem. It's a good opportunity to go through the list of default values and move non-task specific ones to `[default]` as well.

**Comment by forsyth2** [comment]
Note: while addressing this, it may be useful to alphabetize parameters in each section as well.

**Comment by forsyth2** [comment]
It may be good to simply add comments to `default.ini` and direct users there rather than duplicating the parameter list at https://e3sm-project.github.io/zppy/_build/html/main/parameters.html. (Duplication can go out of date quickly).
