### ISSUE TITLE
Fix `atmosphere_only` plotting bug

### ISSUE THREAD

**Issue by forsyth2** [E3SM-Project/zppy#203]
Fix `atmosphere_only` plotting bug.

#160/#161 allowed the global time series plots to work when no MPAS Analysis is available, as is the case for some non-ocean simulations. This worked in E3SM Unified 1.5.1. Unfortunately, #187 broke this functionality -- it fails if `extreme_values` is empty, which is what happens when `atmosphere_only` is set to `True`. Thus, the `atmosphere_only` option does not work properly in E3SM Unified 1.6.0.

A work-around until this fix can be released is to edit a function in `<directory>/post/scripts/global_time_series_<Y1>-<Y2>_dir/coupled_global.py` to begin with:
```
def get_ylim(standard_range, extreme_values):
    standard_min = standard_range[0]
    standard_max = standard_range[1]
    if extreme_values == []:
        return [standard_min, standard_max]
```
Then, from `<directory>/post/scripts/` you can run `sbatch global_time_series_<Y1>-<Y2>.bash`.

**Comment by forsyth2** [comment]
@golaz @xylar Is this bug important enough to justify a patch release of E3SM Unified or at least `zppy`? As mentioned above, there is a work-around.

**Comment by tangq** [comment]
The fix above works for my test.

**Comment by xylar** [comment]
@forsyth2, an E3SM-Unified emergency release is kind of a big deal so I'd say this doesn't rise to that level on its own but if several bugs like this emerge, we can address them.

One advantage of `zppy` is that folks can use the latest development version but still use E3SM-Unified within all the scripts.  That might be a better way to go for now.

**Comment by forsyth2** [comment]
@xylar Thanks, that sounds good. And yes, the `environment_commands` option is useful.
