### ISSUE TITLE
Allow variable values in `ocean_month.py`

### ISSUE THREAD

**Issue by forsyth2** [E3SM-Project/zppy#208]
In `zppy/templates/ocean_month.py`, Lines 32-35, `10` is hard-coded:
```
for y in range(start_yr, end_yr, 10):

    year1 = y
    year2 = y + 10 - 1
```
This was causing issues addressing #128 because the tests were using fewer than 10 years.

A related issue, on line 29: `tunits = "days since 0001-01-01 00:00:00"`, which I believe is only true if we're running from year `0001` and not say `1850`.

**Comment by xylar** [comment]
> A related issue, on line 29: tunits = "days since 0001-01-01 00:00:00", which I believe is only true if we're running from year 0001 and not say 1850.

I don't think this is a problem.  It might be more aesthetic to have:
``` python
tunits = f"days since {start_yr:d04}-01-01 00:00:00"
```
but your later calls to `date2num(` take `tunits` as an argument so they will work as expected regardless of the reference year.

**Comment by xylar** [comment]
```python
year2 = y + 10 - 1
```
Presumably this should be the following?
``` python
year2 = min(y + 10 -1, end_yr)
```
