### ISSUE TITLE
Consider supporting jinja 3

### ISSUE THREAD

**Issue by xylar** [E3SM-Project/zppy#252]
The restriction:
https://github.com/E3SM-Project/zppy/blob/b1957fbff9d44c1b86b1aa5b76fcf3a581589985/conda/meta.yaml#L26
is potentially problematic for the E3SM-Unified ecosystem as other package may start requiring jinja2 >=3 to support newer features.

**Comment by xylar** [comment]
I was also seeing some issues when trying to use `zppy` with `python 3.10` but these seem to be related to some incorrect constraints on `jinaj2` dependencies that I hope will be fixed by:
https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/279

**Comment by forsyth2** [comment]
@xylar I merged #257 to resolve this. Let me know if https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/279 resolved the other issues you saw.

**Comment by xylar** [comment]
Yes, this is all taken care of.  Thank you for #257, I think that will be excellent!
