### ISSUE TITLE
Potential update for NCO invocation

### ISSUE THREAD

**Issue by forsyth2** [E3SM-Project/zppy#254]
Potential update for NCO invocation -- see if `zppy` needs similar changes to https://github.com/E3SM-Project/e3sm_diags/pull/593

**Comment by forsyth2** [comment]
@chengzhuzhang I haven't run into any errors in `zppy` that look related to the NCO updates in https://github.com/E3SM-Project/e3sm_diags/pull/593. Is there something that could come up? Is it best practice to add `--split` and remove `--ypf` for time-series?

**Comment by chengzhuzhang** [comment]
Hi @forsyth2 thanks for checking on this issue. Just to clarify which NCO version are your testing with? The API change could be in the latest NCO 5.0.7 version.

**Comment by forsyth2** [comment]
@chengzhuzhang Oh I see. Yes, the tests run with `"source /lcrc/soft/climate/e3sm-unified/load_latest_e3sm_unified_chrysalis.sh` (https://github.com/E3SM-Project/zppy/blob/main/tests/integration/test_complete_run.cfg#L3). Ok I will need to test with the latest Unified RC then.

**Comment by chengzhuzhang** [comment]
yeah, it would be great to move to test with the latest Unified RC.
