### ISSUE TITLE
Reconsider which `sets` are default for the `e3sm_diags` task

### ISSUE THREAD

**Issue by forsyth2** [E3SM-Project/zppy#259]
Reconsider which `sets` are default for the `e3sm_diags` task. Reducing the number of default sets could make it easier for beginners to run `zppy`.

**Comment by tangq** [comment]
This issue can be related to https://github.com/E3SM-Project/zppy/issues/258 as a typical `cfg` for the production runs is likely to include the commonly used sets, with which new users would like to try. It is another way to define the default sets.

Based on my experience, a working up-to-date, real example is most helpful, in particular for new users.
