### ISSUE TITLE
Omit optional tasks from cfg

### ISSUE THREAD

**Issue by golaz** [E3SM-Project/zppy#29]
Zppy includes some unsupported user-contributed tasks (e.g. amwg). Currently, all the tasks must be listed in the configuration file, even if they are not used. For example:

```
[amwg]
active = False
```

It would be nice if that wasn't needed, but I think removing those is causing problems with the error checking. Maybe a workaround can be found.

**Comment by forsyth2** [comment]
This was achieved by setting the default for `active` to `False` in #184.
