### ISSUE TITLE
Restrucure and installation

### ISSUE THREAD

**Issue by golaz** [E3SM-Project/zppy#30]
If zppy is to be included into the next E3SM Unified, we probably need:

- `zppy` executable instead of `python post.py`.
- Installation code.
- Some code restructure to follow Python convention?

**Comment by chengzhuzhang** [comment]
Hey @xylar. zppy is a new package we would like to be included in next version of `e3sm-unified` 1.5.0. We are aiming for a v1 release for zppy end of May. To be able to include it in e3sm-unified, some restructure is needed, would you advice on best way to package it and make it installable through conda? We will assume users call `zppy` from a computer platform with e3sm-unified installed. Zppy's dependency list should be simple. Thank you!

**Comment by xylar** [comment]
I could help with that.  Some basics of what would need to happen to make this a python package would be:
* move all the code (everything except the `README.md`, `LICENSE` and `.gitignore`) into a `zppy` directory
* rename `post.py` to `__main__.py`
* put the contents of `post.py` in a `main()` function that will become the entry point (`python -m zppy` in test mode, `zppy` in the conda environment)
* add a `setup.py` in the root of the repo
* add a `zppy` entry point that points to `zppy.__main__.main()`
* add a recipe for the conda package

Does someone else want to take this on or should I make a PR after EGU (i.e. early May)?

**Comment by chengzhuzhang** [comment]
Thank you, Xylar. This is great!
@forsyth2 I know you have a list of features to be worked on in May. Not sure about the best timing to do the conversion though,  are you up to do the python packaging following Xylar's instruction?

**Comment by xylar** [comment]
One more thing.  I'm not sure if this is an issue but it's important the `zppy` not try to load E3SM-Unified as part of setting up jobs, since `zppy` itself will live within E3SM-Unified. (It's okay to load E3SM-Unified in job scripts that it creates and launches, thought.)

**Comment by rljacob** [comment]
Yes all our tools can/should assume the user has loaded the E3SM-unified conda package.

**Comment by forsyth2** [comment]
@chengzhuzhang The first 3 of Xylar's bullet points will be easy to implement. The last 3 I would need some more direction on.

**Comment by xylar** [comment]
@forsyth2, here are some tips:

This includes an example `setup.py`:
https://packaging.python.org/tutorials/packaging-projects/

There are lots of other examples you can find in our own repos and elsewhere on GitHub.

Here is an explanation on entry points:
https://amir.rachum.com/blog/2017/07/28/python-entry-points/

The entry point for `zppy` would need to be defined both in `setup.py` and the conda recipe.

Here is the documentation on conda recipes:
https://docs.conda.io/projects/conda-build/en/latest/concepts/recipe.html

Again, there are numerous examples in our repos and also each feedstock on conda-forge is essentially a recipe.

I will, of course, be happy to answer questions as well as review and test what you come up with.

**Comment by xylar** [comment]
I'm going to make some notes based on what @forsyth2 and I just discussed on Webex.

A tricky issue will be that it will be a potential development nightmare that `zppy` is hard-coded to load the latest E3SM-Unified when it is running out of E3SM-Unified.  It would be much better if it uses the `CONDA_EXE` and `CONDA_DEFAULT_ENV` environment variables to determine the conda base path and the name of the conda environment, respectively.  That way, the environment that `zppy` is running out of is also the one that would get loaded in the job script.

This change may be outside the scope of #36 but it should be taken care of before we put the new `zppy` package into E3SM-Unified.

**Comment by xylar** [comment]
My suggestion would be to have a default value for `environment_commands` based on `CONDA_EXE` and `CONDA_DEFAULT_ENV`.  The user could still override this in their own config file.  But then blocks like this:
https://github.com/forsyth2/zppy/blob/a346cf4d4f6f285897e6b2c85af0d96e3b86858a/zppy/templates/e3sm_diags.bash#L5-L9
would always do the "if" part and never the "else".
