### ISSUE TITLE
Include hemispheric averaging

### ISSUE THREAD

**Issue by forsyth2** [E3SM-Project/zppy#302]
Include new hemispheric averaging from NCO. Add figures for hemispheric time-series to global-time-series. To keep backwards-compatibility, we’ll have to check the dimensions: if regional dimension is not there, do what we were doing before. Keep `glb` directory structure?

**Comment by forsyth2** [comment]
@chengzhuzhang @golaz I have some design questions regarding this issue. Thanks!

I see if I add the following block to `zppy/templates/ts.bash`, I can easily process it in `zppy/global_time_series.py` by changing `"atm_monthly_glb"` to `"atm_monthly_rgn"`. Of course, this only a debugging run and not useful as an end-feature.
```
{%- elif mapping_file == 'rgn' -%}
-o output \
--rgn_avg \
--area={{ area_nm }} \
```
Is that the general idea for `ts`? We want users to be able to specify a mapping file `rgn` in another `ts` subtask from the `glb` subtask? I'm unclear how the particular hemisphere (north/south) is specified simply with setting `rgn`.

As for the `global_time_series` task, I see quite a few references to `glb` subdirectories:
```
$ git grep -n glb zppy/templates/
zppy/templates/coupled_global.py:472:            "atmos": "{}/post/atm/glb/ts/monthly/{}yr/glb.xml".format(
zppy/templates/coupled_global.py:477:            else "{}/post/ocn/glb/ts/monthly/{}yr/glb.xml".format(
zppy/templates/coupled_global.py:482:            else "{}/post/ocn/glb/ts/monthly/{}yr/".format(case_dir, ts_num_years),
zppy/templates/coupled_global.py:485:            else "{}/post/ocn/glb/ts/monthly/{}yr/glb.xml".format(
zppy/templates/global_time_series.bash:45:cd ${case_dir}/post/atm/glb/ts/monthly/${ts_num_years}yr
zppy/templates/global_time_series.bash:46:cdscan -x glb.xml *.nc
zppy/templates/global_time_series.bash:57:    mkdir -p ${case_dir}/post/ocn/glb/ts/monthly/${ts_num_years}yr
zppy/templates/global_time_series.bash:69:    cd ${case_dir}/post/ocn/glb/ts/monthly/${ts_num_years}yr
zppy/templates/global_time_series.bash:70:    cdscan -x glb.xml *.nc
zppy/templates/global_time_series.bash:79:    cp ${moc_file} ../../../../../ocn/glb/ts/monthly/${ts_num_years}yr/
zppy/templates/ocean_month.py:18:path_out = "{}/post/ocn/glb/ts/monthly/{}yr".format(case_dir, ts_num_years)
zppy/templates/ocean_month.py:44:    out = "%s/mpaso.glb.%04d01-%04d12.nc" % (path_out, year1, year2)
zppy/templates/ts.bash:77:{%- elif mapping_file == 'glb' -%}
zppy/templates/ts.bash:79:--glb_avg \
```
Do we want to add logic to use a `rgn` subdirectory and/or a `glb` subdirectory depending on the plots chosen? I can set dependencies and other logic in `zppy/global_time_series.py` and `zppy/templates/global_time_series.bash` based on what is set for `plot_names` (https://github.com/E3SM-Project/zppy/blob/main/zppy/templates/default.ini#L274).

**Comment by chengzhuzhang** [comment]
Hi @forsyth2, Aerosol working group has this feature listed as a second tier metrics, I'm a little unsure about the status, could you let me know what this PR cover? I think the goal is to have hemisperical average temperature time series as standard over view plots.

**Comment by forsyth2** [comment]
> I think the goal is to have hemisperical average temperature time series as standard over view plots.

@chengzhuzhang Hmm I thought that was in fact accomplished by #306, but looking at https://web.lcrc.anl.gov/public/e3sm/zppy_test_resources/expected_complete_run/global_time_series/global_time_series_1850-1860_results/v2_historical_0201.pdf, it seems our expected results still just have global plots, rather than plots for each hemisphere... I will need to investigate this further.

**Comment by forsyth2** [comment]
Created #456

**Comment by forsyth2** [comment]
> I think the goal is to have hemisperical average temperature time series as standard over view plots.

@chengzhuzhang #459 resolves this.
