### ISSUE TITLE
Port Cori-specific information to Perlmutter

### ISSUE THREAD

**Issue by forsyth2** [E3SM-Project/zppy#310]
Port Cori-specific information to Perlmutter -- e.g., places in the code/docs mentioning `haswell` or `knl`. Tests should pass on Perlmutter.

**Comment by forsyth2** [comment]
As part of this, move data for integration tests off of `scratch`, which has a 12-week purge policy: https://github.com/E3SM-Project/zppy/blob/main/tests/integration/utils.py#L202

```
        "user_input": "/global/cscratch1/sd/forsyth/",
        "user_output": f"/global/cscratch1/sd/{username}/",
```

**Comment by forsyth2** [comment]
Created #316 for above comment.

**Comment by xylar** [comment]
@forsyth2, I have a PR (still to be tested) for adding `pm-cpu` as a machine: https://github.com/E3SM-Project/mache/pull/59

Please test with that and let me know how it goes.

**Comment by forsyth2** [comment]
#333 partly resolves this issue. It will need to be tested once there is an E3SM Unified release candidate for Perlmutter. Most notably, we need to make sure high-res support still works on Perlmutter:

- `docs/source/campaigns.rst`: access to "bigmem nodes on NERSC Cori" required

**Comment by forsyth2** [comment]
> access to "bigmem nodes on NERSC Cori" required

https://docs.nersc.gov/systems/perlmutter/architecture/#large-memory-nodes: "These nodes are not yet available for user jobs."

-- So, that effectively means we can't run hi-res until Perlmutter large memory nodes become available. Also, they have "1 TB of memory" compared to the "2 TB of RAM" on Cori's large memory nodes (https://docs.nersc.gov/systems/cori-largemem/).

**Comment by forsyth2** [comment]
Moving the specific issue of hi-res support to #355. Closing this larger-scoped issue.
