### ISSUE TITLE
Set mapping file defaults

### ISSUE THREAD

**Issue by forsyth2** [E3SM-Project/zppy#323]
Currently in `zppy`, users have to specify the full path of the mapping file. It would be nice for users to only specify the file name, with `zppy` determining the path automatically. (For backwards compatibility, we'd need to still allow full paths to be set by the `mapping_file` parameter. `zppy` could "guess" the path if a full path isn't provided.)

As discussed in https://github.com/E3SM-Project/mache/issues/53, mapping files will eventually be placed in particular directories -- e.g., for Chrysalis `/lcrc/group/e3sm/public_html/diagnostics/maps` (e.g., in the `/lcrc/group/e3sm/diagnostics` directory, which is the `[diagnostics] > base_path` in https://github.com/E3SM-Project/mache/blob/main/mache/machines/chrysalis.cfg).

So, once the mapping files are placed accordingly, this issue can be addressed.

**Comment by xylar** [comment]
> As discussed in https://github.com/E3SM-Project/mache/issues/53, mapping files will eventually be placed in particular directories

Please go ahead and add mapping files to `/lcrc/group/e3sm/public_html/diagnostics/maps`, just make sure they are group writable.  I (or anyone else with a properly configured `.ssh/config`) can sync them with the command `mache sync diags from chrysalis`.

I would suggest testing on one machine (probably Anvil or Chrysalis).  You will need to get the config parser from mache and use it to call `config.get('diagnostics', 'base_path)`.  Should be easy.
