### ISSUE TITLE
Cannot launch zppy from batch job on chrysalis

### ISSUE THREAD

**Issue by golaz** [E3SM-Project/zppy#329]
Follow-up to https://github.com/E3SM-Project/mache/issues/58.

I was hoping to be able to bypass the issue by just specifying 

`machine = chrysalis`

in the cfg file, but that doesn't work either.

**Comment by forsyth2** [comment]
The issue is that we need `MachineInfo` to get the Unified path at https://github.com/E3SM-Project/zppy/blob/main/zppy/__main__.py#L80

We currently have the below code block after the `MachineInfo` block:
```
    config["default"]["machine"] = machine
    if config["default"]["environment_commands"] == "":
        config["default"]["environment_commands"] = environment_commands
    if config["default"]["account"] == "":
        config["default"]["account"] = account
```

Perhaps we could do something like the following:
```
if tmp:
  if config["default"]["environment_commands"] == ":
        machine_info = MachineInfo()
        unified_base = machine_info.config.get("e3sm_unified", "base_path")
  ...
```
Then, `MachineInfo` would only get called if we don't have the `environment_commands`

**Comment by xylar** [comment]
You need to call `MachineInfo` with the `machine` argument. It should default to `None` if the machine is unknown but should use zppy's `machine` config option if it is provided.

**Comment by xylar** [comment]
I also think you should be using `mache` to figure out what machine you're on rather than having your own logic in zppy to figure this out right after `mache` has just done it.

**Comment by xylar** [comment]
``` python

    # Determine machine to decide which header files to use
    if "machine" in user_config["default"]:
        machine = user_config["default"]["machine"]
    else:
        machine = None
    machine_info = MachineInfo(machine=machine)
    if machine is None:
       machine = machine_info.machine
    # this will be different for cori, so we should figure that out...
    config["default"]["machine"] = machine
    unified_base = machine_info.config.get("e3sm_unified", "base_path")
    environment_commands = (
                f"source {unified_base}/load_latest_e3sm_unified_{machine}.sh"
            )
    account, partition, constraint, qos = machine_info.get_account_defaults()
    ...
```
