### ISSUE TITLE
Zppy error in compy for reference years 

### ISSUE THREAD

**Issue by araman2** [E3SM-Project/zppy#370]
I'm running zppy in compy (version 1.5.1). I see a syntax error in e3sm diags:

/compyfs/rama225/v2.LR.abrupt-1970-aerosol_0301/zppy_output/zppy_abrupt_aerosol_output_latest_v4/post/scripts/e3sm_diags_atm_monthly_180x360_aave_model_vs_obs_0301-0450.o360159

My zppy script is located here: /compyfs/rama225/v2.LR.abrupt-1970-aerosol_0301/zppy_scripts/zppy_aerosol1970_latest.cfg

It looks like a syntax error in e3sm.py

**Comment by forsyth2** [comment]
The error in the `.o` file is:
```
===== RUN E3SM DIAGS model_vs_obs =====

  File "e3sm.py", line 56
    if (ref_end_yr <= ):
                      ^
SyntaxError: invalid syntax
```

This does not match the parameter in your `cfg`:
```
ref_end_year = 2000
```

Change that to:
```
ref_end_yr = 2000
```

For reference, all parameters can be found at https://github.com/E3SM-Project/zppy/blob/main/zppy/templates/default.ini.

Also note for debugging: if you are using E3SM Unified 1.5.1, you are using much older versions of both `zppy` and `e3sm_diags`. Package versions are listed at https://acme-climate.atlassian.net/wiki/spaces/DOC/pages/3236233332/Packages+in+previous+versions+E3SM+Unified+conda+environment#e3sm-unified-1.5.1. E3SM Unified 1.5.1 includes `zppy 1.1.0` and `e3sm_diags 2.6.0`. The upcoming versions in E3SM Unified 1.8 will be `zppy 2.2.0` and `e3sm_diags 2.8.0`.

**Comment by araman2** [comment]
Thanks. That is very helpful to know the default variables. I tried adding other variables for outputs. 
""SWCF,LWCF,FSNTOA,FLUT,FSNT,FLNT,FSNS,FLNS,SHFLX,QFLX,TAUX,TAUY,PRECC,PRECL,PRECSC,PRECSL,TS,TREFHT,CLDTOT,CLDHGH,CLDMED,CLDLOW,U"

I see time series netcdf files for these variables. However, they don't appear in e3sm diags. Error message shows missing climo files. However, I included these variables in the zppy script in the climo section. 

zppy script : /compyfs/rama225/v2.LR.abrupt-1970-aerosol_0301/zppy_scripts/zppy_abrupt_aerosol_1970.cfg

zppy outputs : /compyfs/rama225/v2.LR.abrupt-1970-aerosol_0301/zppy_output/zppy_abrupt_aerosol_output_latest_v5/post/scripts

e3sm diags error : /compyfs/rama225/v2.LR.abrupt-1970-aerosol_0301/zppy_output/zppy_abrupt_aerosol_output_latest_v5/post/scripts/e3sm_diags_atm_monthly_180x360_aave_model_vs_obs_0441-0450.o360945

Variables TAUX, TAUY, CLDMED and TS are not displayed in e3sm diags. The time series netcdf files for these variables are however available /compyfs/rama225/v2.LR.abrupt-1970-aerosol_0301/zppy_output/zppy_abrupt_aerosol_output_latest_v5/post/atm/180x360_aave/ts/

**Comment by forsyth2** [comment]
Great, I'll close the issue then. Let me know if you run into further problems.
