### ISSUE TITLE
Change workflow from `pip` to `mamba/boa` 

### ISSUE THREAD

**Issue by forsyth2** [E3SM-Project/zppy#397]
Change workflow from `pip` to `mamba/boa`

**Comment by tomvothecoder** [comment]
Just leaving this here in case this is useful. You might find another solution fits the needs of `zppy`.

---

I was trying to find the `conda`/`mamba` equivalent of `pip install .` to install a local build of a package. The only command I found was `conda develop .`, which has a slew of issues according to this [post](https://github.com/conda/conda-build/issues/4251).

What I decided to do ([source](https://github.com/conda/conda-build/issues/4251#issuecomment-1053460542)):
 - Stick with `pip install --no-build-isolation --no-deps -e .`
 - With these CLI args `--no-build-isolation --no-deps -e`, no additional dependencies will be installed via `pip`.

Why I decided to do this ([link](https://github.com/xCDAT/xcdat/pull/450/files)):
- I just need to install a local build of the package into `conda` (simple build process)
- All `xcdat` dependencies are already installed in the Anaconda CI environment

Other user's opinions on this:
- https://github.com/conda/conda-build/issues/4251#issuecomment-1053672435
- https://github.com/conda/conda-build/issues/4251#issuecomment-1054123729

**Comment by xylar** [comment]
It's fine to set up a conda/maba environment with the dependencies but then to a `pip install .`.  I had been using `boa` (`conda mambabuild`) in a lot of my testing up to now but I've switched to just installing the dependencies with `mamba` and then installing the package itself with `pip`.

I think the main problem is that you're installing a lot of other packages with `pip`, which isn't great.  All the dependencies should come from conda-forge so you have a consistent set that plays nicely together.

**Comment by tomvothecoder** [comment]
> I think the main problem is that you're installing a lot of other packages with pip, which isn't great. All the dependencies should come from conda-forge so you have a consistent set that plays nicely together.

Yeah for `xcdat` I removed all `pip` packages in `setup.py`, which was especially needed since `xesmf` isn't available on `pip`. `xcdat` uses all `conda-forge` dependencies. 

For `zppy`, we can remove `install_requires` in `setup.py` since the conda environments should already have these dependencies and we don't want to pull in the `pip` versions.

**Comment by xylar** [comment]
You can remove the `install_requires` if you want to.  It's a redundant place to have to keep track of dependencies.

`pip check` won't detect problems anymore but if `install_requires` doesn't get updated properly, that can be more of a hassle than a help in any case.  There should be one definitive place where the dependencies are defined and where we know to look when we're updating the conda-forge feedstock.

**Comment by forsyth2** [comment]
Resolved by #438
