### ISSUE TITLE
Make an independent package for Global Time Series

### ISSUE THREAD

**Issue by forsyth2** [E3SM-Project/zppy#398]
Currently, Global Time Series is fully integrated into `zppy`.

`zppy` is a workflow toolchain / orchestrator of all the various post-processing packages used by E3SM. It coordinates all these external packages -- except for Global Time Series, which is _built into_ it. This means the `zppy` package effectively functions as both a post-processing coordinator AND a global time series generator. These purposes should be separated for better maintainability.

Scoping of effort:
- Create a new repository `global_time_series` under `E3SM-Project`
- Port the following to the new repo:
  - The package-specific code from https://github.com/E3SM-Project/zppy/blob/main/zppy/templates/global_time_series.bash
  - https://github.com/E3SM-Project/zppy/blob/main/zppy/templates/coupled_global.py
  - https://github.com/E3SM-Project/zppy/blob/main/zppy/templates/ocean_month.py
  - https://github.com/E3SM-Project/zppy/blob/main/zppy/templates/readTS.py
- Update the following as needed:
  - https://github.com/E3SM-Project/zppy/blob/main/zppy/templates/default.ini
  - https://github.com/E3SM-Project/zppy/blob/main/zppy/global_time_series.py
  - Files used for testing (while the Global Time Series repository will have its own tests, the package will still be tested indirectly via `zppy` as NCO, E3SM Diags, MPAS-Analysis, ILAMB also are.)
  - Docs mentioning Global Time Series
- Get Global Time Series working as an independent package
  - Would likely still be using Jinja templates. 
  - May want to add configuration files like E3SM Diags has. In particular, #389 still requires users to add plots to modify the code -- can we make it so users can add new plots simply by editing a configuration file?
- Add tests to the new repo
  - Currently, Global Time Series is tested by having `zppy` run `ts` and `mpas_analysis` beforehand. Would we need `zppy` to be in the testing environment to run these tools? That seems like a circular dependency.
- Copy relevant discussion posts to the new repo (or at least make a post linking them): #312, #391

**Comment by xylar** [comment]
Please choose a less generic name than `global_time_series`.  We need something that can go on conda-forge and it can be clear what it computes global time series for.  Maybe give it a non-descriptive but short and memorable name like `zppy`.

**Comment by forsyth2** [comment]
Resolved by #642 and https://github.com/E3SM-Project/zppy-interfaces/pull/1
