### ISSUE TITLE
Add conda build

### ISSUE THREAD

**Issue by forsyth2** [E3SM-Project/zppy#42]
Add conda build for `zppy`. (Note this was initially to be included as part of #30 / #36).

**Comment by xylar** [comment]
I think even if this is done separately, it should be tested before #36 gets merged.  So I don't see a big advantage of doing it separately personally.

**Comment by xylar** [comment]
The reason I say this is that it is only this way that you will discover files missing from the package (e.g. `slurm_header.sh` is currently missing).

It is also not a difficult task and isn't, in my view, clearly separate from making `zppy` a python package.

**Comment by tomvothecoder** [comment]
Hey @forsyth2, if you are going to take this forward in #36 I've provided some references for you:

* [Building conda packages from scratch](https://docs.conda.io/projects/conda-build/en/latest/user-guide/tutorials/build-pkgs.html)
* [My example](https://github.com/tomvothecoder/xcdat/blob/main/conda-recipe/meta.yaml)

Tip: If you include a `build` section in the `meta.yaml`, you don't need a `build.sh` file.

**Comment by forsyth2** [comment]
Closed as part of merging #36.
