### ISSUE TITLE
Consider updating docs to use `mamba` and Mambaforge

### ISSUE THREAD

**Issue by xylar** [E3SM-Project/zppy#427]
I would recommend you update the docs to recommend that folks install [Mambaforge](https://github.com/conda-forge/miniforge#mambaforge) and use `mamba` instead of installing Miniconda3 and using `conda` as the command.  `mamba` is often an order of magnitude or more faster than `conda` for solving packages.  Mambaforge automatically installs `mamba` and also points to `conda-forge`, so it saves confusion and potential errors (such as mixing packages from different channels).

**Comment by golaz** [comment]
We have similar documentation pages as well for zstash and E3SM Diags.

**Comment by xylar** [comment]
Yes, if those pages also still recommend conda and Miniconda, they should be updated similarly.

**Comment by forsyth2** [comment]
I think this is a duplicate (or at least a component of #397

**Comment by xylar** [comment]
@forsyth2, I don't think this is directly related to #397. That is a different workflow. I am referring specifically to https://e3sm-project.github.io/zppy/_build/html/main/getting_started.html#installation-in-a-conda-environment

**Comment by forsyth2** [comment]
I figured #397 would cover changing everything over to mamba.

**Comment by forsyth2** [comment]
@xylar Do you have anything like the docs mentioned here that use `mamba` instead of `conda`? I've never used `mamba` before and I don't even think I have it installed. (`which mamba` shows nothing on Chrysalis.)

**Comment by xylar** [comment]
It needs to be installed explicitly in your base environment if you start with Mimiconda. It comes installed already if you start with Mambaforge (which also makes conda-forge the highest priority channel by default).

Compass and Polaris use mamba extensively and mention it in many places in their docs. Because they included tools for installing it and creating their own conda environments, their docs don't translate one-to-one to zppy and other tools.

If you're uncomfortable make the updates to the docs, I might be able to do it and have you verify that my changes work and make sense.
