### ISSUE TITLE
Cannot generate time series files for all variables

### ISSUE THREAD

**Issue by golaz** [E3SM-Project/zppy#441]
Trying to generate time series files for all variables in a set of input files. With `ncclimo`, this is accomplished by simply omitting the `-v` command line option. 

Unfortunately, this is not possible in `zppy` because `zppy` will always add that option and automatically populate it with an atmosphere default list.

**Comment by forsyth2** [comment]
@golaz It looks like `climo` already had the ability to generate all variables, by specifying `""` for `vars`. I do the same for `ts` in #453.
