### ISSUE TITLE
Expose ncclimo --parallel command line option

### ISSUE THREAD

**Issue by golaz** [E3SM-Project/zppy#442]
In some cases, I found it necessary to change the `--parallel` option in `ncclimo` to successfully generate time series or climo files with `zppy`. But `zppy` currently does not expose that option to the user and so one is forced to manually edit the bash script.

**Comment by forsyth2** [comment]
@golaz `ncclimo` is called in three places -- twice in `climo.bash` and once in `ts.bash`. The 2 `climo` calls had `--parallel=mpi`, so in #452 I changed the parameter value to be user-defined. The `ts` call doesn't use `parallel` though. Should it be conditionally called depending if the user has set a value for it?

**Comment by forsyth2** [comment]
Options:

- Define `parallel = string(default="")` in `[default]`, `parallel = string(default="mpi")` in `[climo]`. As mentioned in #212, this means that the `[climo]` default would override a user-provided value in `[default]`. By default, `climo` would run with `mpi` and `ts` would run without the `parallel` option at all.
- Define `parallel = string(default="mpi")` in `[default]`. Have `ts` run with `mpi` by default, just like `climo`.

**Comment by forsyth2** [comment]
In #452, I go with the first of the above two options, to maintain current functionality by default.
