### ISSUE TITLE
amwg source code is not available on Chrysalis

### ISSUE THREAD

**Issue by xuezhengllnl** [E3SM-Project/zppy#46]
I was trying to run amwg on Chrysalis, but DIAG_HOME is only defined for cori and compy. It would be nice if we can run amwg on Chrysalis.

**Comment by golaz** [comment]
@xuezhengllnl : AMWG under zppy is a user-contributed package and as such it is not officially supported (we should make that clear somewhere in the documentation).

@tangq did the implementation on NERSC, not sure if there are any plans for Chrysalis.

**Comment by xuezhengllnl** [comment]
> @xuezhengllnl : AMWG under zppy is a user-contributed package and as such it is not officially supported (we should make that clear somewhere in the documentation).
> 
> @tangq did the implementation on NERSC, not sure if there are any plans for Chrysalis.

I see. Thanks

**Comment by chengzhuzhang** [comment]
It is a good idea to differentiate standard supported package and user-contributed package. Thanks for the clarification @golaz . 

@xuezhengllnl I'm starting working on annual cycle of zonal mean contour plots(requested by @tangq) and line plots, both will help cover more sets from AMWG. Please feel free to bring up other sets that you'd like to see in e3sm-diags. Thanks

**Comment by tangq** [comment]
@xuezhengllnl , I also added amwg on compy.

@chengzhuzhang , good to know that you are working on the zonal mean plots. I will add the online calculations of stratospheric and tropospheric ozone columns soon, so we can easily have the lat-lon ozone column plots.

**Comment by chengzhuzhang** [comment]
@tangq Adding online calculation of these quantities will be great! Thanks for the heads-up.

**Comment by tangq** [comment]
We will have 3 ozone column quantities: total, stratospheric, and tropospheric. total = strat + trop.

But only 2 of them will be default output to save the disk space.

@chengzhuzhang , saving which 2 variables will be easier for e3sm_diags to create the 3 lat-lon plots? Or perhaps it does't matter?

**Comment by chengzhuzhang** [comment]
@tangq Yes, having strat and trop will be good enough. It's straightforward to derive total based on both.
