### ISSUE TITLE
Make `e3sm_to_cmip` its own task

### ISSUE THREAD

**Issue by forsyth2** [E3SM-Project/zppy#467]
Make `e3sm_to_cmip` its own task rather than being an optional part of the `ts` task.

**Comment by chengzhuzhang** [comment]
Some notes for using `e3sm_to_cmip`:
-  land and atmosphere variables needs remapped nc files as input.
-  MPAS variables depends on native outputs and need auxiliary files ( same as what MPAS analysis does)
- For v3 output, we will likely to add more variables in cmorized list
- cmorized data has a specific directory structure
- Consider try out the [end-to-end script](https://github.com/E3SM-Project/e3sm_to_cmip/blob/master/scripts/example_end-to-end_script.sh).
