### ISSUE TITLE
Unified rc12 testing: `diags_environment_commands` doesn't seem to be set up properly for Compy

### ISSUE THREAD

**Issue by forsyth2** [E3SM-Project/zppy#482]
```
$ zppy -c tests/integration/generated/test_complete_run_compy.cfg
$ cd /compyfs/fors729/zppy_test_complete_run_output/v2.LR.historical_0201/post/scripts
$ grep "ERROR" *status
e3sm_diags_atm_monthly_180x360_aave_environment_commands_model_vs_obs_1850-1851.status:ERROR (5)
e3sm_diags_atm_monthly_180x360_aave_environment_commands_model_vs_obs_1850-1853.status:ERROR (5)
e3sm_diags_atm_monthly_180x360_aave_environment_commands_model_vs_obs_1852-1853.status:ERROR (5)
$ cat e3sm_diags_atm_monthly_180x360_aave_environment_commands_model_vs_obs_1850-1851.o553041 
Could not find conda environment: e3sm_diags_20230816
You can list all discoverable environments with `conda info --envs`.

/tmp/slurmd/job553041/slurm_script: line 121: cdscan: command not found
```

From the `cfg`:
`environment_commands = "source /qfs/people/fors729/miniconda3/etc/profile.d/conda.sh; conda activate e3sm_diags_20230816"` (set by `"diags_environment_commands": "source /qfs/people/fors729/miniconda3/etc/profile.d/conda.sh; conda activate e3sm_diags_20230816",` in `tests/integration/utils.py`).

**Comment by xylar** [comment]
@forsyth2, do you have leads on this problem or do you need help?

**Comment by forsyth2** [comment]
@xylar I think I've resolved this. Looks like the `conda` activation line just needed to be updated to use `mamba`. (Strangely that didn't seem to cause an issue on Chrysalis or Perlmutter though).
