### ISSUE TITLE
Location for ocean and seaice history set to "run".

### ISSUE THREAD

**Issue by rljacob** [E3SM-Project/zppy#500]
I was running zppy on a case that was run without a run script but all output was moved to the archive dir with the case.st_archive command.

In the mpas-analysis config file created by zppy, the locations for ocean and sea ice history were:
oceanHistorySubdirectory = /lcrc/group/e3sm/jacob/scratch/chrys/archive/WCYCLtrbilin//run
seaIceHistorySubdirectory = /lcrc/group/e3sm/jacob/scratch/chrys/archive/WCYCLtrbilin//run

They should be:
oceanHistorySubdirectory = /lcrc/group/e3sm/jacob/scratch/chrys/archive/WCYCLtrbilin/ocn/hist
seaIceHistorySubdirectory = /lcrc/group/e3sm/jacob/scratch/chrys/archive/WCYCLtrbilin/ice/hist

In the main zppy config file, the default input and output are:
input = /lcrc/group/e3sm/jacob/scratch/chrys/archive/WCYCLtrbilin
output = /lcrc/group/e3sm/jacob/scratch/chrys/archive/WCYCLtrbilin

**Comment by forsyth2** [comment]
These are set automatically at https://github.com/E3SM-Project/zppy/blob/main/zppy/mpas_analysis.py#L42:

```
        if config["mpas_analysis"]["shortTermArchive"]:
            c["subdir_ocean"] = "/archive/ocn/hist"
            c["subdir_ice"] = "/archive/ice/hist"
        else:
            c["subdir_ocean"] = "/run"
            c["subdir_ice"] = "/run"
```

The directories are defined at https://github.com/E3SM-Project/zppy/blob/main/zppy/templates/mpas_analysis.bash#L180:
```
oceanHistorySubdirectory = {{ input }}/{{ subdir_ocean }}
seaIceHistorySubdirectory = {{ input }}/{{ subdir_ice }}
```

It sounds like the request here is to allow the `subdir_ocean` and `subdir_ice` parameters to be user-supplied, if need be? is that correct?

**Comment by rljacob** [comment]
No I think see the problem.  I had "shortTermArchive = False" in the mpas_analysis section of my zppy config file.  That must be it.
