### ISSUE TITLE
Automate docs using CI/CD

### ISSUE THREAD

**Issue by tomvothecoder** [E3SM-Project/zppy#51]
Automate docs with PR merges to `master` and new tag releases.

This issue was originally apart of #43, but was separated for ease of implementation.

Requirements
- [ ] Move documentation over to `master` from `gh-pages`
- [ ] Add publish docs job to build workflow
  - Reference [link](https://github.com/E3SM-Project/e3sm_diags/blob/fc9180f8e64bba53b3a02bf96dc887a877cf83bd/.github/workflows/build_workflow.yml#L92)
- [ ] Add publish docs job to release workflow
   - Reference [link](https://github.com/E3SM-Project/e3sm_diags/blob/fc9180f8e64bba53b3a02bf96dc887a877cf83bd/.github/workflows/release_workflow.yml#L8) 
 - [ ] QA - docs publish on fork's GitHub Pages

**Comment by forsyth2** [comment]
Similar to https://github.com/E3SM-Project/zstash/pull/122
