### ISSUE TITLE
Option to not include casename in model_vs_model diagnostic plot filename

### ISSUE THREAD

**Issue by wlin7** [E3SM-Project/zppy#522]
It looks like default that casename is used to name e3sm_diags generated image file for model_vs_model comparison, for example

Here is a [model_vs_model e3sm_diags](https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.wlin/E3SMv3_dev/20230929.v3alpha04-COARE.F2010.chrysalis/e3sm_diags/atm_monthly_180x360_aave_mvm/v3alpha04-COARE_vs_v3alpha04-CTL_0002-0011/viewer/) for v3alpha04 F2010 run using default vs COARE 3.0 ocean surface flux scheme.

The PRECT plot filename is [20230825.pre-v3alpha03.F2010.chrysalis-PRECT-ANN-global.png](https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.wlin/E3SMv3_dev/20230929.v3alpha04-COARE.F2010.chrysalis/e3sm_diags/atm_monthly_180x360_aave_mvm/v3alpha04-COARE_vs_v3alpha04-CTL_0002-0011/lat_lon/model_vs_model/20230918.v3alpha03-ncexp1p1.F2010.chrysalis-PRECT-ANN-global.png).

The earlier version of e3sm_diags produced the plots without casename in the image filename, say, just [-PRECT-ANN-global.png](https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.wlin/v3.NGD.AtmPhys/P3_ZMmicro//PSA.F2010-P3.v3atm_pre/PSA.F2010-P3.v3atm_pre_mincdnc/e3sm_diags/180x360_aave/model_vs_base_0001-0005_vs_0001-0005/lat_lon/model_vs_model/-PRECT-ANN-global.png)

For general purpose, this is not an issue. But [IICE ](https://acme-climate.atlassian.net/wiki/spaces/IPD/pages/3718709487/IICE+Interface+for+Inter-Comparison+of+E3SM+diagnostics)(comparison viewer of multiple diags), with minimum input from user specifying URL to the top viewer page alone, does not try to a determine casename associated with the diags, leaving it unable to correctly set the URL path to the image for display.

Do we already have such an option? Or was there any concern leading to the change by including casename? What if we change to not include casename in the filename, just like for model_vs_obs diags?

**Comment by chengzhuzhang** [comment]
One possibility is to include a new parameter to avoid including `ref_name` in plot name, which convert `ref_name = ""` in the e3sm_diags script.

**Comment by chengzhuzhang** [comment]
@forsyth2 when you get a chance, can you help with this issue. This seems to block using IICE with e3sm_diags output.

**Comment by forsyth2** [comment]
> can you help with this issue. This seems to block using IICE with e3sm_diags output.

Is the request to include a new parameter, in time for the Unified patch release?

**Comment by chengzhuzhang** [comment]
If including a new parameter could work without other complications, adding this for the Unified patch release will be great!

**Comment by forsyth2** [comment]
Is the issue only on climo links? What about climo_diurnal? `case` shows up a decent amount in the `zppy` code.

```
$ git grep -n "\${case}"
templates/e3sm_diags.bash:150:create_links_climo ${climo_dir_source} ${climo_dir_primary} ${case} ${Y1} ${Y2} 1
templates/e3sm_diags.bash:167:create_links_climo_diurnal ${climo_diurnal_dir_source} ${climo_diurnal_dir_primary} ${case} ${Y1} ${Y2} 3
templates/e3sm_diags.bash:254:param.test_name = '${case}'
templates/e3sm_diags.bash:479:web_dir=${www}/${case}/e3sm_diags/{{ sub }}
templates/global_time_series.bash:112:f=${www}/${case}/global_time_series
templates/global_time_series.bash:135:rsync -a --delete ${results_dir_absolute_path} ${www}/${case}/global_time_series
templates/global_time_series.bash:144:pushd ${www}/${case}/global_time_series
templates/global_time_series.bash:152:pushd ${www}/${case}/global_time_series
templates/ilamb.bash:44:mkdir -p ${model_root}/${case}
templates/ilamb.bash:45:cd ${model_root}/${case}
templates/ilamb.bash:85:web_dir=${www}/${case}/ilamb/{{ sub }}_${Y1}-${Y2}
templates/mpas_analysis.bash:325:f=${www}/${case}/mpas_analysis/${identifier}/
templates/mpas_analysis.bash:347:rsync -a --delete ${identifier}/html/ ${www}/${case}/mpas_analysis/${identifier}/
templates/mpas_analysis.bash:355:pushd ${www}/${case}/mpas_analysis/
templates/mpas_analysis.bash:363:pushd ${www}/${case}/mpas_analysis/
```

**Comment by forsyth2** [comment]
> It seems like zppy won't proceed with generating symlinks for climo files

So, the generating of links is the only problem that needs fixing in `zppy` correct? And we want to accomplish that with a `no_case` parameter? 

(I.e., I don't need to change how zppy creates output paths or anything like that?)

**Comment by chengzhuzhang** [comment]
The issue is not to have case name in figure names, to work with IICE. IICE prefers a name like `-PRECT-ANN-global.png`. But with `ref_name` given, the figures take names as `ref_name-PRECT-ANN-global.png`. one possibility is not to change how zppy create symlinks, but have a `no_case_name_in_fig` parameter to revert `ref_name` to empty string for generating `e3sm_diags` run script.

**Comment by chengzhuzhang** [comment]
@wlin7 can clarify, but I think we want this `no_case_name_in_fig` in parameter as default for model-vs-model?
