### ISSUE TITLE
iLAMB with zppy generated no figures 

### ISSUE THREAD

**Issue by xuezhengllnl** [E3SM-Project/zppy#523]
I added an ilamb section in my zppy cfg for v3alpha04.trigrid.bgc run
[https://github.com/E3SM-Project/SimulationScripts/blob/master/archive/CoupledGroup/v3_dev/post.20231012.v3alpha04_trigrid_bgc.piControl.chrysalis.cfg](url)
It ran and created a web link [https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.xzheng/E3SMv3_dev/20231012.v3alpha04_trigrid_bgc.piControl.chrysalis/ilamb/180x360_aave_0091-0100/](url) 
But there is no figure or result in the link to me. 
The zppy ilamb log file is /lcrc/group/e3sm2/ac.xzheng/E3SMv3_dev/20231012.v3alpha04_trigrid_bgc.piControl.chrysalis/post/scripts/ilamb_0091-0100.o410331
Thanks,

**Comment by forsyth2** [comment]
Relevant Confluence page: https://acme-climate.atlassian.net/wiki/spaces/CM/pages/3951656961/20231012.v3alpha04+trigrid+bgc.piControl.chrysalis

**Comment by forsyth2** [comment]
The output file begins with:
```
cp: cannot stat '/lcrc/group/e3sm2/ac.xzheng/E3SMv3_dev/20231012.v3alpha04_trigrid_bgc.piControl.chrysalis/post/lnd/180x360_aave/cmip_ts/monthly//*_*_*_*_*_*_0091??-0100??.nc': No such file or directory
cp: cannot stat '/lcrc/group/e3sm2/ac.xzheng/E3SMv3_dev/20231012.v3alpha04_trigrid_bgc.piControl.chrysalis/post/atm/180x360_aave/cmip_ts/monthly//*_*_*_*_*_*_0091??-0100??.nc': No such file or directory
```

```
$ ls /lcrc/group/e3sm2/ac.xzheng/E3SMv3_dev/20231012.v3alpha04_trigrid_bgc.piControl.chrysalis/post/lnd
native
# No `180x360_aave` directory
```
=> I think you would need to have a `[[ land_monthly_180x360_aave]]` subtask because you set `grid = '180x360_aave'` for `[ilamb]`.

```
$ ls /lcrc/group/e3sm2/ac.xzheng/E3SMv3_dev/20231012.v3alpha04_trigrid_bgc.piControl.chrysalis/post/atm/180x360_aave/
clim  clim_diurnal_8xdaily  ts
# No `cmip_ts` directory
```
=> Add `ts_fmt = "cmip"` to `[[ atm_monthly_180x360_aave ]]` (and `[[ land_monthly ]]`)

**Comment by chengzhuzhang** [comment]
Thank you for trouble shooting @forsyth2 ! 
This again reminds us that adding more support for land analysis will be another priority.

**Comment by xuezhengllnl** [comment]
> The output file begins with:
> 
> ```
> cp: cannot stat '/lcrc/group/e3sm2/ac.xzheng/E3SMv3_dev/20231012.v3alpha04_trigrid_bgc.piControl.chrysalis/post/lnd/180x360_aave/cmip_ts/monthly//*_*_*_*_*_*_0091??-0100??.nc': No such file or directory
> cp: cannot stat '/lcrc/group/e3sm2/ac.xzheng/E3SMv3_dev/20231012.v3alpha04_trigrid_bgc.piControl.chrysalis/post/atm/180x360_aave/cmip_ts/monthly//*_*_*_*_*_*_0091??-0100??.nc': No such file or directory
> ```
> 
> ```
> $ ls /lcrc/group/e3sm2/ac.xzheng/E3SMv3_dev/20231012.v3alpha04_trigrid_bgc.piControl.chrysalis/post/lnd
> native
> # No `180x360_aave` directory
> ```
> 
> => I think you would need to have a `[[ land_monthly_180x360_aave]]` subtask because you set `grid = '180x360_aave'` for `[ilamb]`.
> 
> ```
> $ ls /lcrc/group/e3sm2/ac.xzheng/E3SMv3_dev/20231012.v3alpha04_trigrid_bgc.piControl.chrysalis/post/atm/180x360_aave/
> clim  clim_diurnal_8xdaily  ts
> # No `cmip_ts` directory
> ```
> 
> => Add `ts_fmt = "cmip"` to `[[ atm_monthly_180x360_aave ]]` (and `[[ land_monthly ]]`)

Thanks @forsyth2, I added these settings to the cfg file (see the updated cfg below). The generated ilamb link still has no result. 
[https://github.com/E3SM-Project/SimulationScripts/blob/master/archive/CoupledGroup/v3_dev/post.20231012.v3alpha04_trigrid_bgc.piControl.chrysalis.cfg](url)

**Comment by forsyth2** [comment]
Thanks @xuezhengllnl, I will try to look into this more this afternoon. Sometimes coming up with the right parameter settings can be tricky.

**Comment by forsyth2** [comment]
@xuezhengllnl Hmm you're actually making it further than me. I'm running this:
```
[default]
input = /lcrc/group/e3sm2/ac.xzheng/E3SMv3_dev/20231012.v3alpha04_trigrid_bgc.piControl.chrysalis
output = /lcrc/group/e3sm/ac.forsyth2/n523/20231012.v3alpha04_trigrid_bgc.piControl.chrysalis
#output = /lcrc/group/e3sm2/ac.xzheng/E3SMv3_dev/20231012.v3alpha04_trigrid_bgc.piControl.chrysalis
case = 20231012.v3alpha04_trigrid_bgc.piControl.chrysalis
www = /lcrc/group/e3sm/public_html/diagnostic_output/ac.forsyth2/n523
#www = /lcrc/group/e3sm/public_html/diagnostic_output/ac.xzheng/E3SMv3_dev
partition = compute 
environment_commands = "source /lcrc/soft/climate/e3sm-unified/load_e3sm_unified_1.9.0_chrysalis.sh"

[ts]
active = True
walltime = "0:30:00"
years = "0051:0100:50",

  [[ atm_monthly_180x360_aave ]]
  input_subdir = "archive/atm/hist"
  input_files = "eam.h0"
  mapping_file = /home/ac.zender/data/maps/map_ne30pg2_to_cmip6_180x360_aave.20200201.nc
  frequency = "monthly"
  vars = "FSNTOA,FLUT,FSNT,FLNT,FSNS,FLNS,SHFLX,QFLX,TAUX,TAUY,PRECC,PRECL,PRECSC,PRECSL,TS,TREFHT,CLDTOT,CLDHGH,CLDMED,CLDLOW,U,ICEFRAC,LANDFRAC,OCNFRAC,AODALL,AODBC,AODDUST,AODPOM,AODSO4,AODSOA,AODSS,AODVIS,PS,CO_SRF,TCO,TROP_P"
  ts_fmt = "cmip"

  [[ atm_daily_180x360_aave ]]
  input_subdir = "archive/atm/hist"
  input_files = "eam.h1"
  mapping_file = /home/ac.zender/data/maps/map_ne30pg2_to_cmip6_180x360_aave.20200201.nc
  frequency = "daily"
  vars = "PRECT"

  [[ atm_monthly_glb ]]
  input_subdir = "archive/atm/hist"
  input_files = "eam.h0"
  mapping_file = "glb"
  frequency = "monthly"
  years = "0001:0050:50"

  [[ land_monthly ]]
  input_subdir = "archive/lnd/hist"
  input_files = "elm.h0"
  mapping_file = "" 
  frequency = "monthly"
  vars = "FSH,RH2M"
  extra_vars = "landfrac"
  ts_fmt = "cmip"

  [[ rof_monthly ]]
  input_subdir = "archive/rof/hist"
  input_files = "mosart.h0"
  mapping_file = ""
  frequency = "monthly"
  vars = "RIVER_DISCHARGE_OVER_LAND_LIQ"
  extra_vars = 'areatotal2'

  [[ land_monthly_180x360_aave]]

  [[atm_hourly_US1.0x1.0_nco]]
  mapping_file = /home/ac.lee1061/ChemDyg_inputs/maps/map_ne30pg2_to_MDA8US1.0x1.0_nco.20211202.nc
  input_files = "eam.h4"
  frequency = "hourly"
  vars = "O3_SRF"
  dpf = 10
  tpd = 24

  [[atm_hourly_EU1.0x1.0_nco]]
  mapping_file = /home/ac.lee1061/ChemDyg_inputs/maps/map_ne30pg2_to_MDA8EU1.0x1.0_nco.20211202.nc
  input_files = "eam.h4"
  frequency = "hourly"
  vars = "O3_SRF"
  dpf = 10
  tpd = 24
 
[ilamb]
active = True
nodes = 8
walltime = "2:00:00"
partition = compute 
short_name = '20231012.v3alpha04_trigrid_bgc.piControl.chrysalis'
ts_num_years = 50
years = "0051:0100:50"
```

And getting this error on `ts_land_monthly_0051-0100-0050.o416602 ` (so, ILAMB can't even run):
```
2023-11-01 20:53:58,968_968:INFO:__init__:--------------------------------------
2023-11-01 20:53:58,969_969:INFO:__init__:| E3SM to CMIP Configuration
2023-11-01 20:53:58,969_969:INFO:__init__:--------------------------------------
2023-11-01 20:53:58,969_969:INFO:__init__:    * var_list='['mrsos', 'mrso', 'mrfso', 'mrros', 'mrro', 'prveg', 'evspsblveg', 'evspsblsoi', 'tran', 'tsl', 'lai', 'cLitter', 'cProduct', 'cS\
oilFast', 'cSoilMedium', 'cSoilSlow', 'fFire', 'fHarvest', 'cVeg', 'nbp', 'gpp', 'ra', 'rh']'
2023-11-01 20:53:58,969_969:INFO:__init__:    * input_path='/lcrc/group/e3sm/ac.forsyth2/n523/20231012.v3alpha04_trigrid_bgc.piControl.chrysalis/post/lnd/native/ts/monthly/50yr'
2023-11-01 20:53:58,969_969:INFO:__init__:    * output_path='/lcrc/group/e3sm/ac.forsyth2/n523/20231012.v3alpha04_trigrid_bgc.piControl.chrysalis/post/lnd/native/cmip_ts/monthly/tmp_ts_la\
nd_monthly_0051-0100-0050'
2023-11-01 20:53:58,969_969:INFO:__init__:    * precheck_path='None'
2023-11-01 20:53:58,969_969:INFO:__init__:    * freq='mon'
2023-11-01 20:53:58,969_969:INFO:__init__:    * realm='lnd'
2023-11-01 20:53:58,969_969:INFO:__init__:    * Writing log output file to: logs/20231101_205358_962591
2023-11-01 20:54:14,428_428:WARNING:derive_handlers:No handlers could be derived for the variables: ['mrsos', 'mrso', 'mrfso', 'mrros', 'mrro', 'prveg', 'evspsblveg', 'evspsblsoi', 'tran'\
, 'tsl', 'lai', 'cLitter', 'cProduct', 'cSoilFast', 'cSoilMedium', 'cSoilSlow', 'fFire', 'fHarvest', 'cVeg', 'nbp', 'gpp', 'ra', 'rh']. Make sure the input E3SM datasets have the variable\
s needed derivation.
2023-11-01 20:54:14,428_428:INFO:_get_handlers:--------------------------------------
2023-11-01 20:54:14,428_428:INFO:_get_handlers:| Derived CMIP6 Variable Handlers
2023-11-01 20:54:14,428_428:INFO:_get_handlers:--------------------------------------
2023-11-01 20:54:14,428_428:ERROR:_get_handlers:No CMIP6 variable handlers were derived from the variables found in using the E3SM input datasets.
srun: error: chr-0252: task 0: Exited with exit code 1
```

**Comment by forsyth2** [comment]
@xuezhengllnl Sorry, I haven't had a chance to do more debugging yet, due to the upcoming E3SM Unified patch release. Have you had a chance to check if you did link your latest cfg? I'm not sure why I'm getting different results than you...

**Comment by forsyth2** [comment]
@mahf708 @chengzhuzhang If one of you has spare time, can you try running the cfg above (https://github.com/E3SM-Project/zppy/issues/523#issuecomment-1789785569, you'll need to change the `output` and `www` to be your own directories) and see if you run into the same issue as me or if you get further? I'm wondering if it's a me-specific problem. Thanks!

**Comment by chengzhuzhang** [comment]
I have submitted a zppy run with Xue's config, will update the my finding aft the run finish...

**Comment by chengzhuzhang** [comment]
@forsyth2 the error you reported is caused by missing land variables that `e3sm_to_cmip` require. None of the land variables `vars = "FSH,RH2M"` can convert to any land cmip variable. So I extended the var list to below: 

```
  [[ land_monthly ]]
  input_subdir = "archive/lnd/hist"
  input_files = "elm.h0"
  mapping_file = "" 
  frequency = "monthly"
  vars = "FSH,RH2M,LAISHA,LAISUN,QINTR,QOVER,QRUNOFF,QSOIL,QVEGE,QVEGT,SOILICE,SOILLIQ,SOILWATER_10CM,TSA,TSOI,H2OSNO"
  extra_vars = "landfrac"
  ts_fmt = "cmip"
```
This would by pass the error you had, but new error occur:

```
2023-11-10 02:49:08,870_870:INFO:run_parallel:0 of 11 handlers complete
2023-11-10 02:49:08,871_871:ERROR:run_parallel:evspsblveg, tsl, mrsos, prveg, evspsblsoi, lai, mrros, mrro, tran, mrfso, mrso failed to complete
2023-11-10 02:49:08,871_871:ERROR:run_parallel:0 of 11 handlers complete
'lat_bnds'
'lat_bnds'
'lat_bnds'
'lat_bnds'
'lat_bnds'
'lat_bnds'
'lat_bnds'
'lat_bnds'
'lat_bnds'
'lat_bnds'
'lat_bnds'
mv: cannot stat '/lcrc/group/e3sm/ac.zhang40/tests/20231012.v3alpha04_trigrid_bgc.piControl.chrysalis/post/lnd/native/cmip_ts/monthly/tmp_ts_land_monthly_0051-0100-0050/CMIP6/CMIP/*/*/*/*/*/*/*/*/*.nc': No such file or directory
```

The tri-grid dataset does not have `lat_bnds`! And it occurred to me that we had a discussion before, see https://github.com/E3SM-Project/zppy/discussions/373#discussioncomment-4357280 and https://github.com/E3SM-Project/zppy/discussions/373#discussioncomment-4458180 gave an solution to remap the `r05` native tri-grid output to standard `cmip6_180x360_aave` grids to get the bounds back and make `e3sm_to_cmip` work!

**Comment by chengzhuzhang** [comment]
I think we should add some standard r05 maps to our standard maps here: https://web.lcrc.anl.gov/public/e3sm/diagnostics/maps/ to better support upcomming  tri-grids output processing. I'm not sure if it is worthwhile to add `lat_bnds` and `lon_bnds` to native ELM output, seeking @czender's advice...

**Comment by chengzhuzhang** [comment]
Looked up the cf-convention. In general, it is recommended to supply cell bounds whenever possible. But it should be fairly straightforward to add bounds during post-processing.

**Comment by czender** [comment]
There are a few considerations regarding bounds variables. As you note above, the regridder adds the bounds variables to the regridded output, so long as the destination grid is FV (finite volume), including dual grid representations of SE (spectral element), so that's one option. It is also possible to place bounds variables in the native ELM output, i.e., to add that functionality to EAM itself. However, it's ill defined what the bounds would be in SE mode (not really an issue since v2, v3 are FV). Also, bi-grid runs use the pg2 grid for ELM, and pg2 grids are not rectangular, so the bounds variables would need to be four (lat,lon) vertices per gridcell. That means a timeseries file with a single field, temperature say, would use 10x the storage for the grid information as it does for the field information. Tri-grid runs usually use r05 grids, which are rectangular, so the bounds variables can be simple 1D arrays for lat and lon, and the grid overhead is minimal. Let me know if you'd like me to add any r05-to-cmip map-files to https://web.lcrc.anl.gov/public/e3sm/diagnostics/maps.

**Comment by chengzhuzhang** [comment]
@czender thank you for weighing in! 
I added two new mapse to support r05-to_cmip: map_r05_cmip6_180x360_aave.20231110.nc and map_r05_cmip6_180x360_nco.20231110.nc. It looks like `mono` is no longer a valid option in latest nco, so I just skipped. 

I still think it is worthwhile to add `lat-bnds` and `lon-bnds` to the native `r05` output, so the datasets can be more readily to be used as-is for analysis purpose. Though I don't know how much development work is needed in ELM and time-wise if we can still squeeze it in for v3. This should be decided by the land group, pinging @bishtgautam on this issue. 

In the mean time I added a new issue in `e3sm_to_cmip` to support datasets that don't have lat lon bounds attached.

**Comment by czender** [comment]
Sounds good to me. Note that your new maps are missing the word "_to_" and thus do not comply with the old naming convention. (The v3 naming convention is different still, see [here](https://acme-climate.atlassian.net/wiki/spaces/DOC/pages/1217757434/Mapping+file+algorithms+and+naming+convention)). There are multiple types of monotonic maps and the one you want can be obtained by invoking ncremap with -`-alg_typ=traave` (the new naming convention, supported in E3SMU 1.9.1/NCO 5.1.9) or `--alg_typ=fv2fv_flx`.

**Comment by chengzhuzhang** [comment]
Thank you for reviewing and pointing out the new naming convention for map files..Though I'm still confused and not sure if I provide the right command. Does below look right?:
`ncremap -s r05_360x720.20200901.nc -g cmip6_180x360_scrip.20181001.nc -a aave -m /lcrc/group/e3sm/public_html/diagnostics/maps/map_r05_to_cmip6_180x360_ncoaave.20231110.nc`

**Comment by chengzhuzhang** [comment]
Thank you @czender! Now I get the recommended changes for v3 mapping file naming convention, it aligns with ncremap's -a argument values!. I will update the maps once /lcrc/group/e3sm back on line.

**Comment by rljacob** [comment]
I agree to not bother with cell bounds if the grids are not rectangular (and only the river grids in E3SM are rectangular).

**Comment by forsyth2** [comment]
@chengzhuzhang @czender Thanks for looking into this further.

> None of the land variables vars = "FSH,RH2M" can convert to any land cmip variable

That problem sounds familiar, but it still doesn't answer why @xuezhengllnl's run got further than mine, when we had the same configuration.

> I have generated 3 files and saved at /lcrc/group/e3sm/public_html/diagnostics/maps/

Should I try to rerun now and see if the ILAMB figures generate?

**Comment by chengzhuzhang** [comment]
> I agree to not bother with cell bounds if the grids are not rectangular (and only the river grids in E3SM are rectangular).

Yes! it looks like we have two sets of river/land grids, r0125 and r05, which will be relevant to v3 simulation campaigns.

**Comment by chengzhuzhang** [comment]
@xuezhengllnl and @forsyth2 By extending the variable list, and specifying one of the r05_to_cmip mapping files. The ilamb figures generated.
Here is the .cfg file section I changed:

```
  [[ land_monthly ]]
  input_subdir = "archive/lnd/hist"
  input_files = "elm.h0"
  mapping_file = "/lcrc/group/e3sm/public_html/diagnostics/maps/map_r05_to_cmip6_180x360_esmfaave.20231110.nc" 
  frequency = "monthly"
  vars = "FSH,RH2M,LAISHA,LAISUN,QINTR,QOVER,QRUNOFF,QSOIL,QVEGE,QVEGT,SOILICE,SOILLIQ,SOILWATER_10CM,TSA,TSOI,H2OSNO"
  extra_vars = "landfrac"
  ts_fmt = "cmip"
```

**Comment by czender** [comment]
> Thank you @czender! Now I get the recommended changes for v3 mapping file naming convention, it aligns with ncremap's -a argument values!. I will update the maps once /lcrc/group/e3sm back on line.

To be clear, these are all new algorithm names that were recently agreed to in the new convention. Once we agreed to the new naming convention, I added these algorithm names as synonyms to the existing (and new, for TR bilinear) algorithms that ncremap supports. The first version of NCO that supports invocation by these algorithm names is 5.1.9, which is in the E3SMU-1.9.1 "emergency" release. Once I have time I will verify and support the new convention for MBTR as well, and expect that to be in NCO 5.2.0 in ~December.

**Comment by forsyth2** [comment]
@chengzhuzhang @czender Thank you! I was able to generate the ILAMB plots using this cfg:

```
# Matches https://github.com/E3SM-Project/zppy/issues/523#issuecomment-1809312288
[default]
input = /lcrc/group/e3sm2/ac.xzheng/E3SMv3_dev/20231012.v3alpha04_trigrid_bgc.piControl.chrysalis
output = /lcrc/group/e3sm/ac.forsyth2/n523v6/20231012.v3alpha04_trigrid_bgc.piControl.chrysalis
#output = /lcrc/group/e3sm2/ac.xzheng/E3SMv3_dev/20231012.v3alpha04_trigrid_bgc.piControl.chrysalis
case = 20231012.v3alpha04_trigrid_bgc.piControl.chrysalis
www = /lcrc/group/e3sm/public_html/diagnostic_output/ac.forsyth2/n523v6
#www = /lcrc/group/e3sm/public_html/diagnostic_output/ac.xzheng/E3SMv3_dev
partition = compute 
environment_commands = "source /lcrc/soft/climate/e3sm-unified/load_e3sm_unified_1.9.0_chrysalis.sh"

[ts]
active = True
walltime = "0:30:00"
years = "0051:0100:50",

  [[ atm_monthly_180x360_aave ]]
  input_subdir = "archive/atm/hist"
  input_files = "eam.h0"
  mapping_file = /home/ac.zender/data/maps/map_ne30pg2_to_cmip6_180x360_aave.20200201.nc
  frequency = "monthly"
  vars = "FSNTOA,FLUT,FSNT,FLNT,FSNS,FLNS,SHFLX,QFLX,TAUX,TAUY,PRECC,PRECL,PRECSC,PRECSL,TS,TREFHT,CLDTOT,CLDHGH,CLDMED,CLDLOW,U,ICEFRAC,LANDFRAC,OCNFRAC,AODALL,AODBC,AODDUST,AODPOM,AODSO4,AODSOA,AODSS,AODVIS,PS,CO_SRF,TCO,TROP_P"
  ts_fmt = "cmip"

  [[ atm_daily_180x360_aave ]]
  input_subdir = "archive/atm/hist"
  input_files = "eam.h1"
  mapping_file = /home/ac.zender/data/maps/map_ne30pg2_to_cmip6_180x360_aave.20200201.nc
  frequency = "daily"
  vars = "PRECT"

  [[ atm_monthly_glb ]]
  input_subdir = "archive/atm/hist"
  input_files = "eam.h0"
  mapping_file = "glb"
  frequency = "monthly"
  years = "0001:0050:50"

  [[ land_monthly ]]
  input_subdir = "archive/lnd/hist"
  input_files = "elm.h0"
  mapping_file = "/lcrc/group/e3sm/public_html/diagnostics/maps/map_r05_to_cmip6_180x360_esmfaave.20231110.nc" 
  frequency = "monthly"
  vars = "FSH,RH2M,LAISHA,LAISUN,QINTR,QOVER,QRUNOFF,QSOIL,QVEGE,QVEGT,SOILICE,SOILLIQ,SOILWATER_10CM,TSA,TSOI,H2OSNO"
  extra_vars = "landfrac"
  ts_fmt = "cmip"

  [[ rof_monthly ]]
  input_subdir = "archive/rof/hist"
  input_files = "mosart.h0"
  mapping_file = ""
  frequency = "monthly"
  vars = "RIVER_DISCHARGE_OVER_LAND_LIQ"
  extra_vars = 'areatotal2'

  [[ land_monthly_180x360_aave]]

  [[atm_hourly_US1.0x1.0_nco]]
  mapping_file = /home/ac.lee1061/ChemDyg_inputs/maps/map_ne30pg2_to_MDA8US1.0x1.0_nco.20211202.nc
  input_files = "eam.h4"
  frequency = "hourly"
  vars = "O3_SRF"
  dpf = 10
  tpd = 24

  [[atm_hourly_EU1.0x1.0_nco]]
  mapping_file = /home/ac.lee1061/ChemDyg_inputs/maps/map_ne30pg2_to_MDA8EU1.0x1.0_nco.20211202.nc
  input_files = "eam.h4"
  frequency = "hourly"
  vars = "O3_SRF"
  dpf = 10
  tpd = 24
 
[ilamb]
active = True
nodes = 8
walltime = "2:00:00"
partition = compute 
short_name = '20231012.v3alpha04_trigrid_bgc.piControl.chrysalis'
ts_num_years = 50
years = "0051:0100:50"
```
See https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.forsyth2/n523v6/20231012.v3alpha04_trigrid_bgc.piControl.chrysalis/ilamb/_0051-0100/

**Comment by chengzhuzhang** [comment]
I'm providing an updated .cfg for `ilamb` here, because it seems that the cfg here https://github.com/E3SM-Project/zppy/issues/523#issuecomment-1810696311, only enabled atmospheric variables in the ilamb results.

```
[default]
input = /lcrc/group/e3sm2/ac.xzheng/E3SMv3_dev/20231012.v3alpha04_trigrid_bgc.piControl.chrysalis
output = /lcrc/group/e3sm/ac.zhang40/tests/20231012.v3alpha04_trigrid_bgc.piControl.chrysalis_ilamb_try2
case = 20231012.v3alpha04_trigrid_bgc.piControl.chrysalis
www = /lcrc/group/e3sm/public_html/diagnostic_output/ac.zhang40/tests/E3SMv3_dev/ilamb
partition = compute 
environment_commands = "source /lcrc/soft/climate/e3sm-unified/load_e3sm_unified_1.9.0_chrysalis.sh"


[ts]
active = True
walltime = "0:30:00"
years = "0051:0100:50",

  [[ atm_monthly_180x360_aave ]]
  input_subdir = "archive/atm/hist"
  input_files = "eam.h0"
  mapping_file = /home/ac.zender/data/maps/map_ne30pg2_to_cmip6_180x360_aave.20200201.nc
  frequency = "monthly"
  vars = "FSNTOA,FLUT,FSNT,FLNT,FSNS,FLNS,SHFLX,QFLX,TAUX,TAUY,PRECC,PRECL,PRECSC,PRECSL,TS,TREFHT,CLDTOT,CLDHGH,CLDMED,CLDLOW,U,ICEFRAC,LANDFRAC,OCNFRAC,AODALL,AODBC,AODDUST,AODPOM,AODSO4,AODSOA,AODSS,AODVIS,PS,CO_SRF,TCO,TROP_P"
  ts_fmt = "cmip"


  [[ land_monthly]]
  input_subdir = "archive/lnd/hist"
  input_files = "elm.h0"
  mapping_file = "/lcrc/group/e3sm/public_html/diagnostics/maps/map_r05_to_cmip6_180x360_aave.20231110.nc" 
  frequency = "monthly"
  vars = "FSH,RH2M,LAISHA,LAISUN,QINTR,QOVER,QRUNOFF,QSOIL,QVEGE,QVEGT,SOILICE,SOILLIQ,SOILWATER_10CM,TSA,TSOI,H2OSNO"
  extra_vars = "landfrac"
  ts_fmt = "cmip"


[ilamb]
active = True
nodes = 8
walltime = "2:00:00"
partition = compute 
short_name = '20231012.v3alpha04_trigrid_bgc.piControl.chrysalis'
ts_num_years = 50
years = "0051:0100:50"


  [[ land_monthly ]]

```

**Comment by xuezhengllnl** [comment]
@chengzhuzhang @forsyth2, Thank you so much for your help on this! I generated the ILAMB plots with your cfg settings. Here is the link: [https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.xzheng/E3SMv3_dev/20231117.v3b02.piControl.chrysalis/ilamb/_0351-0400/]

I'm closing this issue now.

**Comment by chengzhuzhang** [comment]
@xuezhengllnl thank you for reporting back, in the ilamb results you recently generated, it still seems like only atmosphere variables are created. Maybe try the new config here would give the land diagnostics plots: https://github.com/E3SM-Project/zppy/issues/523#issuecomment-1816911763

**Comment by chengzhuzhang** [comment]
@xuezhengllnl To follow up on supporting more bgc variables. Below is my updated variable list:
vars = "FSH,RH2M,LAISHA,LAISUN,QINTR,QOVER,QRUNOFF,QSOIL,QVEGE,QVEGT,SOILICE,SOILLIQ,SOILWATER_10CM,TSA,TSOI,H2OSNO,TOTLITC,CWDC,SOIL1C,SOIL2C,SOIL3C,SOIL4C,WOOD_HARVESTC,TOTVEGC,NBP,GPP,AR,HR" for `land_monthly` task
Note to myself : two of the variables used to be saved in v1/v2 were not available in the recent `tri_grid_bgc` run, including: `COL_FIRE_CLOSS` and `TOTPRODC`. Here is my [ILAMB results](https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.zhang40/tests/E3SMv3_dev/ilamb_bgc/20231012.v3alpha04_trigrid_bgc.piControl.chrysalis/ilamb/land_monthly_0051-0100/).
In addition, I still have some ilamb errors that caused some variable (e.g LAI) to fail to generate plots. [An issue](https://github.com/rubisco-sfa/ILAMB/issues/83) has been filed with ILAMB.

**Comment by xuezhengllnl** [comment]
> @xuezhengllnl To follow up on supporting more bgc variables. Below is my updated variable list: vars = "FSH,RH2M,LAISHA,LAISUN,QINTR,QOVER,QRUNOFF,QSOIL,QVEGE,QVEGT,SOILICE,SOILLIQ,SOILWATER_10CM,TSA,TSOI,H2OSNO,TOTLITC,CWDC,SOIL1C,SOIL2C,SOIL3C,SOIL4C,WOOD_HARVESTC,TOTVEGC,NBP,GPP,AR,HR" for `land_monthly` task Note to myself : two of the variables used to be saved in v1/v2 were not available in the recent `tri_grid_bgc` run, including: `COL_FIRE_CLOSS` and `TOTPRODC`. Here is my [ILAMB results](https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.zhang40/tests/E3SMv3_dev/ilamb_bgc/20231012.v3alpha04_trigrid_bgc.piControl.chrysalis/ilamb/land_monthly_0051-0100/). In addition, I still have some ilamb errors that caused some variable (e.g LAI) to fail to generate plots. [An issue](https://github.com/rubisco-sfa/ILAMB/issues/83) has been filed with ILAMB.

@chengzhuzhang Thank you so much for your suggestions. I generated more ilamb diagnostics with your updated setting. Here is the [ILAMB link](https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.xzheng/E3SMv3_dev/20231117.v3b02.piControl.chrysalis/ilamb/land_monthly_0441-0450/)

**Comment by forsyth2** [comment]
Note for myself: Test `zppy` with ILAMB 2.7. Check that both atmosphere and land plots were generated. We shouldn't have to do a `[[ land_monthly ]]` subtask (as in https://github.com/E3SM-Project/zppy/issues/523#issuecomment-1816911763). If `LeafAreaIndex` variables (E3SM native names: `LAISHA,LAISUN`) are present and cmorized (CMIP name: `lai`), then the ILAMB plots should be created.

**Comment by chengzhuzhang** [comment]
Update: with updated v2.7 of ILAMB, more results are generated: https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.zhang40/tests/E3SMv3_dev/ilamb_bgc_eu1.9.2rc2/20231012.v3alpha04_trigrid_bgc.piControl.chrysalis/ilamb/land_monthly_0051-0100/, i.e. Leaf aera index related plots generated. There are some remaining issues, (e.g. only a subset of biomass diagnostics shown up). Those should be discussed with land bgc developers.
