### ISSUE TITLE
Make Zppy citable with Zenodo

### ISSUE THREAD

**Issue by chengzhuzhang** [E3SM-Project/zppy#606]
### Request criteria

- [X] I searched the [zppy GitHub Discussions](https://github.com/E3SM-Project/zppy/discussions) to find a similar question and didn't find it.
- [X] I searched the [zppy documentation](https://e3sm-project.github.io/zppy).
- [X] This issue does not match the other templates (i.e., it is not a bug report, documentation request, feature request, or a question.)

### Issue description

I think we should consider use the data archiving tool [Zenodo](https://about.zenodo.org/)  and get a DOI for zpp so it can be cited in papers.https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content

**Comment by forsyth2** [comment]
Thanks @chengzhuzhang. I suppose we should do this for zstash too.

**Comment by forsyth2** [comment]
Does this apply DOIs to previous releases or would it only be going forward?

**Comment by chengzhuzhang** [comment]
I think new DOIs will be issued each time a GitHub release is made, I guess we don't need to worry about previous releases in this case. 

Good to have DOIs for both zstash and zppy since we don't have a way to cite at this point.

**Comment by forsyth2** [comment]
@chengzhuzhang I just followed the directions at https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content

## Before toggling zppy on
![Screenshot 2024-08-02 at 12 29 09 PM](https://github.com/user-attachments/assets/02cc3211-d882-480c-923a-e106bcc6aeed)

Notice zstash apparently already has a DOI. However, it's not showing up on the repo's README: https://github.com/E3SM-Project/zstash. https://gist.github.com/seignovert/ae6771f400ca464d294261f42900823a shows how to add it there.

## After toggling zppy on
I ran the "To the right of the name of the repository you want to archive, toggle the button to On." step and got:
![Screenshot 2024-08-02 at 12 30 25 PM](https://github.com/user-attachments/assets/84375e63-9056-44e9-b1ee-12105c3a0b2b)
I guess once we make the next zppy release, we'll see if this worked for real.

**Comment by chengzhuzhang** [comment]
@forsyth2 thank you!

**Comment by forsyth2** [comment]
https://github.com/E3SM-Project/zstash/pull/342 adds the DOI badge to zstash.
