### ISSUE TITLE
Consider ways for providing different defaults for different machines, meshes and science campaigns

### ISSUE THREAD

**Issue by xylar** [E3SM-Project/zppy#66]
My recent PRs (#63, #64 and #65) made clear to me that there isn't currently a clear mechanism for providing different default config options in `zppy` for different machines or meshes.  There are several performance options in MPAS-Analysis that need to be set up differently for low- vs. high-res MPAS-Ocean and -Seaice meshes.  I strongly suspect (and #9 seems to confirm) that the same is true for E3SM_Diags and its associated `ncclimo` calls.

Our supported machines are also configured somewhat differently in E3SM-Unified.  I couldn't get ESMF to compile with system MPI on Cori, so mapping-file generation needs to happen in serial there.  But it can (and should) happen in parallel on other machines.  For now, I'm hard-coding serial mapping-file generation on Cori in #63, which is fine.  But it does seem like other config options will come up where hard coding for each machine isn't the right option (users should ideally still be able to change the option) but the default should be different on different machines.

Finally, as I mentioned on Thursday, it would seem like a good idea to have different default configurations for the different science campaigns.  The Cryosphere campaign needs a lot more analysis than zppy runs by default.  It would also be my preference that WC settings not be prioritized as the defaults, but rather be given equal footing to the defaults for the other science campaigns.

By the way, we haven't found a great solution to these issues in MPAS-Analysis, and this is the reason for having a large number of clumsy and outdated examples in our `configs` directory.

**Comment by golaz** [comment]
@xylar : The Water Cycle focus was simply a result of zppy being developed as a Water Cycle effort initially. I totally agree that we need to incorporate more flexibility.  It seems to me that we have at least two dimensions:

1. Machine specific settings (cori, chrysalis, ...)
2. Targeted use (Water Cycle, Cryosphere, ...)

I can envision a number of ways to achieve extra flexibility, but I don't know what would work best for you. (There may also be options that I haven't thought of.)

1. Customize the template, like you have done in your recent PRs. Easy and straight forward, until it's too messy.
2. Maintain multiple templates (Water Cycle, Cryosphere, ...) and add a high level selector in zppy.
3. For machine specific settings, they could be abstracted and templatized elsewhere (especially if they need to be reused).
4. We could also consider having multiple MPAS Analysis tasks (although that is not my preferred option).

I assume you are also facing a similar challenge without using zppy. How do you handle it? Do you provide customized cfg files for targeted machines and uses? Does everyone make their own custom cfg file?

I'm happy to discuss options in more details.

**Comment by xylar** [comment]
@golaz, yes, we can keep doing 1. above and I also like the idea of 2.  So far, it seems like selectors are enough for 3. but there will likely come a time when a separate, machine-specific config file out help.  I agree with you that different MPAS-Analysis tasks (e.g. one for WC and one for Cryo) doesn't sound like a straightforward option, so let's not do 4.

> I assume you are also facing a similar challenge without using zppy. How do you handle it? Do you provide customized cfg files for targeted machines and uses? Does everyone make their own custom cfg file?

It seems to be working well in E3SM-Unified and compass to have a config file for each machine, so I would recommend that approach.  The idea is that you ingest the default config file, then the machine config file, and finally the user's config file so they have the option to override the machine defaults wherever that makes sense.

We also have default config options for the Cryo campaign in a config file for MPAS-Analysis.  That has also worked well.  Users provide the cryo config file, then the custom config file at the command line (so the custom config file overrides the cryo defaults wherever needed).

MPAS-Analysis doesn't do a good job at providing machine-specific defaults.  We have a bunch of examples but we don't try to identify the machine or anything like that.  That was partly based on my experience with A-Prime, where I felt that too much emphasis had been placed on running on specific machines and not enough on robustly in general, regardless of machine.  I still think the individual diagnostics tools (MPAS-Analysis, E3SM_Diags, NCO, etc.) shouldn't get too attached to specific machines so I think zppy provides a great service in being a machine- and project-specific layer above those tools.

Anyway, let's keep the dialog going.  There's no rush to figure this out, nor any need to get it right on the first try.  Just worth experimenting with.

**Comment by xylar** [comment]
@forsyth2, this is an open-ended issue and it has been partially dealt with.  I suggest we close it and open more targeted issues related to it as needed.

**Comment by forsyth2** [comment]
> I suggest we close it and open more targeted issues related to it as needed.

Different defaults for:
- different machines: #240/#244
- meshes: I don't think there are any issues/PRs for this
- science campaigns: #135/#138 (water cycle), #144 (cryosphere), #151 (BGC)

@xylar Should I just close this issue and create a issue to provide different defaults for meshes then?

**Comment by xylar** [comment]
> @xylar Should I just close this issue and create a issue to provide different defaults for meshes then?

I think the need for this hasn't yet arisen, expect that it would probably be very difficult to run zppy on E3SM high-res ocean meshes without a lot of tweaks.  You can open an issue if you like but it might be fine to wait for now and let folks that run into difficulties open more specific issues as needed.

**Comment by forsyth2** [comment]
Ok sounds good, I'll close this issue and we can open specific issues as they arise.
