### ISSUE TITLE
Several nonstandard Exceptions

### ISSUE THREAD

**Issue by xylar** [E3SM-Project/zppy#67]
In general, a `ValueError` is the right default exception name.  A generic `Exception` should not be raised.  If you print an error and then raise an exception, the printed error message gets lost above the stack trace.

There are several cases of exceptions I found to be unhelpful get raised in zppy.  Here are the ones I have run into so far:
https://github.com/E3SM-Project/zppy/blob/8f1c80cfc4eae36731a759be74b3d6f5998cf7f6/zppy/utils.py#L93-L94
This should be:
``` python
            raise ValueError("Could not interpret years %s" % (years))
```

https://github.com/E3SM-Project/zppy/blob/8f1c80cfc4eae36731a759be74b3d6f5998cf7f6/zppy/utils.py#L113

https://github.com/E3SM-Project/zppy/blob/8f1c80cfc4eae36731a759be74b3d6f5998cf7f6/zppy/utils.py#L153-L156

**Comment by xylar** [comment]
@forsyth2, was this already taken care of?

**Comment by xylar** [comment]
I guess not based on a quick search of the code.

**Comment by forsyth2** [comment]
I just created #266 to resolve this.
