### ISSUE TITLE
post.py not found

### ISSUE THREAD

**Issue by tangq** [E3SM-Project/zppy#71]
The documentation says that one can run zppy with `python ~/E3SM/code/zppy/post.py -c post.mysimulation.cfg`, but post.py is not available in the current version.

How to use the latest version? Thanks.

**Comment by forsyth2** [comment]
@tangq The documentation is not currently up-to-date. Please note that `zppy` is officially still in pre-release. We plan to have the documentation updated by the official release date of July 1 (See #40).

**Comment by forsyth2** [comment]
The command will be `zppy -c <configuration file>`.

**Comment by tangq** [comment]
@forsyth2 , thanks for the information. Does it require some kind of installation before I can run `zppy -c <configuration file>`? I don't see `zppy` in the zppy folder.

**Comment by forsyth2** [comment]
It will be part of the E3SM Unified environment. The updated documentation will also include installation steps if you don't want to use the unified environment.

**Comment by tangq** [comment]
Can you send me the installation commands? I updated my zppy on chrysalis and it stopped working. Thanks.

**Comment by forsyth2** [comment]
If you have the latest commits in your clone of the `zppy` repo, then you can run the following:
```
cd <zppy repo>
conda env create -f conda/dev.yml
conda activate zppy_dev
pip install .
zppy -c <configuration-file>
```

**Comment by forsyth2** [comment]
Note that `zppy` will use the latest official release of E3SM unified environment to run E3SM Diags, MPAS-Analysis, etc.

**Comment by tangq** [comment]
Thanks, @forsyth2 .

**Comment by tangq** [comment]
@forsyth2 , zppy was installed successfully with the commands above, but it failed with a previously working configuration file. The errors are pasted below. Do you have any clues what the cause might be?
```
(zppy_dev) [ac.qtang@chrlogin1 post]$ zppy -c post.20210603.v2rc3c.piControl.northamericax4v1pg2_WC14to60E2r3.chrysalis.cfg 
Validation results={'default': True, 'climo': True, 'ts': True, 'e3sm_diags': {'active': True, 'grid': True, 'qos': True, 'nodes': True, 'walltime': True, 'reference_data_path': True, 'short_name': True, 'cfg': True, 'sets': True, 'backend': True, 'diff_title': True, 'run_type': True, 'tag': True, 'output_format': True, 'output_format_subplot': True, 'multiprocessing': True, 'num_workers': True, 'vars': True, 'climo_diurnal_subsection': True, '180x360_aave': True, 'conus_0.23x0.31_aave': {'active': True, 'grid': True, 'qos': True, 'nodes': True, 'walltime': True, 'reference_data_path': True, 'short_name': True, 'cfg': True, 'sets': False, 'backend': True, 'diff_title': True, 'run_type': True, 'tag': True, 'output_format': True, 'output_format_subplot': True, 'multiprocessing': True, 'num_workers': True, 'vars': True, 'climo_diurnal_subsection': True}}, 'e3sm_diags_vs_model': True, 'mpas_analysis': True, 'amwg': True, 'global_time_series': True}
Traceback (most recent call last):
  File "/home/ac.qtang/.conda/envs/zppy_dev/bin/zppy", line 8, in <module>
    sys.exit(main())
  File "/home/ac.qtang/.conda/envs/zppy_dev/lib/python3.7/site-packages/zppy/__main__.py", line 33, in main
    raise Exception('Configuration file validation failed')
Exception: Configuration file validation failed
```

**Comment by forsyth2** [comment]
`sets` is `False` for your `conus_0.23x0.31_aave` subsection. That means `sets` is not formatted correctly. It must be formatted like `sets = "lat_lon","zonal_mean_xy",` -- notice comma at the end.

**Comment by tangq** [comment]
That's interesting. The comma was not required in the previous version. I added it and it pasted the failing point.

Now, here is the new errors. Is 'ts_num_years' a new setting?
```
  File "/home/ac.qtang/.conda/envs/zppy_dev/lib/python3.7/site-packages/zppy/templates/e3sm_diags.bash", line 61, in top-level template code
    ts_dir={{ output }}/post/atm/{{ grid }}/ts/monthly/{{ '%dyr' % (ts_num_years) }}
jinja2.exceptions.UndefinedError: 'ts_num_years' is undefined
```

**Comment by forsyth2** [comment]
Yes, for any E3SM Diags set that requires time series, you will need to include `ts_num_years`, which is the size of the time-series chunks that should be used. (e.g., if `years = "1:100:10",` in the `[ts]` section, then you should set `ts_num_years=10` in the `[e3sm_diags]` section).

**Comment by tangq** [comment]
Now it complains about `jinja2.exceptions.TemplateNotFound: e3sm_diags/lat_lon_conus.cfg`

I see this file in the zppy repo directory, 
```
(zppy_dev) [ac.qtang@chrlogin1 post]$ ls /home/ac.qtang/E3SM/code/zppy/zppy/templates/e3sm_diags/lat_lon_conus.cfg
/home/ac.qtang/E3SM/code/zppy/zppy/templates/e3sm_diags/lat_lon_conus.cfg
```

but not in conda directory.
```
(zppy_dev) [ac.qtang@chrlogin1 post]$ ls /home/ac.qtang/.conda/envs/zppy_dev/lib/python3.7/site-packages/zppy/templates/e3sm_diags/lat_lon_conus.cfg
ls: cannot access '/home/ac.qtang/.conda/envs/zppy_dev/lib/python3.7/site-packages/zppy/templates/e3sm_diags/lat_lon_conus.cfg': No such file or directory
```

It still fails even when I changed the path from cfg = "e3sm_diags/lat_lon_conus.cfg" to cfg = "/home/ac.qtang/E3SM/code/zppy/zppy/templates/e3sm_diags/lat_lon_conus.cfg"

**Comment by tangq** [comment]
When I removed the `conus_0.23x0.31_aave` subsection in e3sm_diags, it doesn't recognize the correct climo dependency file.
```
...skipping because of dependency status file missing
   /lcrc/group/e3sm/ac.qtang/E3SM_simulations/20210603.v2rc3c.piControl.northamericax4v1pg2_WC14to60E2r3.chrysalis/post/scripts/climo__0041-0060.status
```

**Comment by forsyth2** [comment]
@tangq Can you send me/post your configuration file? I will try to debug, thanks.

**Comment by tangq** [comment]
@forsyth2 , you can find a copy here: https://github.com/E3SM-Project/SimulationScripts/blob/master/archive/v2/rc/coupled/post.20210603.v2rc3c.piControl.northamericax4v1pg2_WC14to60E2r3.chrysalis.cfg

The conus subsection was commented out, but should be turned on when it's working. Thanks.

**Comment by forsyth2** [comment]
> Now it complains about `jinja2.exceptions.TemplateNotFound: e3sm_diags/lat_lon_conus.cfg`

I am able to duplicate this error. I'm wondering if the path to the `cfg` while needs to change now that we use `zppy` instead of `python zppy/post.py`. @xylar Is this possibly related to #44?

**Comment by chengzhuzhang** [comment]
@forsyth2 I noticed that .cfg is not included in `data_files` in `setup.py`. could it be a related?
data_files = package_files('zppy', prefixes=[], extensions=['bash', 'csh', 'ini', 'sh'])

**Comment by forsyth2** [comment]
> @forsyth2 I noticed that .cfg is not included in `data_files` in `setup.py`. could it be a related?
> data_files = package_files('zppy', prefixes=[], extensions=['bash', 'csh', 'ini', 'sh'])

@chengzhuzhang Thanks, yes that is the problem. `cfg` has to be added to `extensions`.  That will require a pull request to `zppy` -- not sure if we want to include that in a `rc3` pre-release?

@tangq Furthermore, `ts_num_years` should only be set for the subsection `180x360_aave`, not the entire `e3sm_diags` section. 

> ```
> ...skipping because of dependency status file missing
>    /lcrc/group/e3sm/ac.qtang/E3SM_simulations/20210603.v2rc3c.piControl.northamericax4v1pg2_WC14to60E2r3.chrysalis/post/scripts/climo__0041-0060.status
> ```

I'm still looking into this issue. `sub` isn't being set properly it seems.

**Comment by chengzhuzhang** [comment]
> @chengzhuzhang Thanks, yes that is the problem. `cfg` has to be added to `extensions`. That will require a pull request to `zppy` -- not sure if we want to include that in a `rc3` pre-release?
Yes. I think a PR is needed to fix this and to be included in next release.

**Comment by forsyth2** [comment]
> When I removed the `conus_0.23x0.31_aave` subsection in e3sm_diags, it doesn't recognize the correct climo dependency file.
> 
> ```
> ...skipping because of dependency status file missing
>    /lcrc/group/e3sm/ac.qtang/E3SM_simulations/20210603.v2rc3c.piControl.northamericax4v1pg2_WC14to60E2r3.chrysalis/post/scripts/climo__0041-0060.status
> ```

@tangq This error is caused because `"diurnal_cycle"` is automatically included as a set to run, but you don't have `climo` set up to produce the necessary files. If you set `sets` to be exclude it, you'll run into another dependency issue, this time with the time series. That will be fixed by renaming all `180x360_aave` sections to `atm_monthly_180x360_aave`.

This is how your E3SM Diags section should look:
```
[e3sm_diags]
active = True
reference_data_path = '/lcrc/soft/climate/e3sm_diags_data/obs_for_e3sm_diags/climatology'
output_format_subplot = "pdf",
short_name = '20210603.v2rc3c.piControl.naRRM'
years = "1:60:20",

  [[atm_monthly_180x360_aave]]
  grid = '180x360_aave'
  sets = "lat_lon","zonal_mean_xy","zonal_mean_2d","polar","cosp_histogram","meridional_mean_2d","enso_diags","qbo","area_mean_time_series",
  ts_num_years=10

  [[conus_0.23x0.31_aave]]
  grid = 'conus_0.23x0.31_aave'
  sets = 'lat_lon',
  cfg = "e3sm_diags/lat_lon_conus.cfg"
```

**Comment by forsyth2** [comment]
> > @chengzhuzhang Thanks, yes that is the problem. `cfg` has to be added to `extensions`. That will require a pull request to `zppy` -- not sure if we want to include that in a `rc3` pre-release?
> 
> Yes. I think a PR is needed to fix this and to be included in next release.

Resolved in #73.

**Comment by forsyth2** [comment]
@tangq I was able to run the modified configuration file, but the atm_monthly_180x360_aave E3SM Diags failed -- you'll also need to set `ref_start_yr`.
```
File "e3sm.py", line 14
    ref_start_yr =
                  ^
SyntaxError: invalid syntax
```

**Comment by tangq** [comment]
> > When I removed the `conus_0.23x0.31_aave` subsection in e3sm_diags, it doesn't recognize the correct climo dependency file.
> > ```
> > ...skipping because of dependency status file missing
> >    /lcrc/group/e3sm/ac.qtang/E3SM_simulations/20210603.v2rc3c.piControl.northamericax4v1pg2_WC14to60E2r3.chrysalis/post/scripts/climo__0041-0060.status
> > ```
> 
> @tangq This error is caused because `"diurnal_cycle"` is automatically included as a set to run, but you don't have `climo` set up to produce the necessary files. If you set `sets` to be exclude it, you'll run into another dependency issue, this time with the time series. That will be fixed by renaming all `180x360_aave` sections to `atm_monthly_180x360_aave`.
> 
> This is how your E3SM Diags section should look:
> 
> ```
> [e3sm_diags]
> active = True
> reference_data_path = '/lcrc/soft/climate/e3sm_diags_data/obs_for_e3sm_diags/climatology'
> output_format_subplot = "pdf",
> short_name = '20210603.v2rc3c.piControl.naRRM'
> years = "1:60:20",
> 
>   [[atm_monthly_180x360_aave]]
>   grid = '180x360_aave'
>   sets = "lat_lon","zonal_mean_xy","zonal_mean_2d","polar","cosp_histogram","meridional_mean_2d","enso_diags","qbo","area_mean_time_series",
>   ts_num_years=10
> 
>   [[conus_0.23x0.31_aave]]
>   grid = 'conus_0.23x0.31_aave'
>   sets = 'lat_lon',
>   cfg = "e3sm_diags/lat_lon_conus.cfg"
> ```

Thanks, @forsyth2 . Does this require changing the climo section to [[atm_monthly_180x360_aave]] as well, so the e3sm_diags section can find the right climo dependency?

**Comment by tangq** [comment]
> @tangq I was able to run the modified configuration file, but the `atm_monthly_180x360_aave` E3SM Diags failed -- you'll also need to set `ref_start_yr`.
> 
> ```
> File "e3sm.py", line 14
>     ref_start_yr =
>                   ^
> SyntaxError: invalid syntax
> ```

I didn't encounter this issue when I made the changes you recommended.

**Comment by tangq** [comment]
@forsyth2 , another thing is that I didn't update my zppy repo and reinstall it, but the "e3sm_diags/lat_lon_conus.cfg" error disappeared automatically. Why is that?

**Comment by tangq** [comment]
I did encounter the `ref_start_yr =` error. What number should be set to it?

**Comment by forsyth2** [comment]
> Does this require changing the climo section to [[atm_monthly_180x360_aave]] as well, so the e3sm_diags section can find the right climo dependency?

Yes that one needs to be changed too.

> another thing is that I didn't update my zppy repo and reinstall it, but the "e3sm_diags/lat_lon_conus.cfg" error disappeared automatically. Why is that?

That's surprising. I just merged #73 today so I don't see how that error would have gone away for you.

> I did encounter the ref_start_yr = error later. What number should be set to it?

You set `ref_start_yr` and `ref_end_yr` to whatever years you want for the observation. You also have to set `obs_ts` in the (e.g. `obs_ts = '/lcrc/soft/climate/e3sm_diags_data/obs_for_e3sm_diags/time-series'`). For example:
```
[e3sm_diags]
active = True
reference_data_path = '/lcrc/soft/climate/e3sm_diags_data/obs_for_e3sm_diags/climatology'
output_format_subplot = "pdf",
short_name = '20210603.v2rc3c.piControl.naRRM'
years = "1:60:20",

  [[atm_monthly_180x360_aave]]
  grid = '180x360_aave'
  sets = "lat_lon","zonal_mean_xy","zonal_mean_2d","polar","cosp_histogram","meridional_mean_2d","enso_diags","qbo","area_mean_time_series",
  ts_num_years = 10
  obs_ts = '/lcrc/soft/climate/e3sm_diags_data/obs_for_e3sm_diags/time-series'
  ref_start_yr = 1990
  ref_end_yr = 1999

  [[conus_0.23x0.31_aave]]
  grid = 'conus_0.23x0.31_aave'
  sets = 'lat_lon',
  cfg = "e3sm_diags/lat_lon_conus.cfg"
```
I'm waiting for that to finish running but it does successfully submit the batch jobs.

**Comment by forsyth2** [comment]
You'll also need to set `ref_final_yr`, which is the last year the observation data covers. (`ref_end_yr` isn't strictly required). Try:
```
[e3sm_diags]
active = True
reference_data_path = '/lcrc/soft/climate/e3sm_diags_data/obs_for_e3sm_diags/climatology'
output_format_subplot = "pdf",
short_name = '20210603.v2rc3c.piControl.naRRM'
years = "1:60:20",

  [[atm_monthly_180x360_aave]]
  grid = '180x360_aave'
  sets = "lat_lon","zonal_mean_xy","zonal_mean_2d","polar","cosp_histogram","meridional_mean_2d","enso_diags","qbo","area_mean_time_series",
  ts_num_years = 10
  obs_ts = '/lcrc/soft/climate/e3sm_diags_data/obs_for_e3sm_diags/time-series'
  ref_start_yr = 1990
  ref_end_yr = 1999
  ref_final_yr = 2016

  [[conus_0.23x0.31_aave]]
  grid = 'conus_0.23x0.31_aave'
  sets = 'lat_lon',
  cfg = "e3sm_diags/lat_lon_conus.cfg"
```

**Comment by tangq** [comment]
@forsyth2 , I'd like to update to the current main for #73 before I try your suggestions. What are the commands to reinstall zppy?

**Comment by forsyth2** [comment]
> What are the commands to reinstall zppy?
```
git fetch upstream main
git rebase upstream/main
conda env remove --name zppy_dev
conda env create -f conda/dev.yml
conda activate zppy_dev
pip install .
```

**Comment by tangq** [comment]
@forsyth2 , after reinstalling zppy, the e3sm_diags configurations work fine except the sets in the conus subsection need to change to the new format `"lat_lon",` from the old one `['lat_lon']`.

**Comment by forsyth2** [comment]
@tangq Glad it's working!

**Comment by forsyth2** [comment]
Closing this issue since it appears everything is working.
