### ISSUE TITLE
Command line arguments too long

### ISSUE THREAD

**Issue by golaz** [E3SM-Project/zppy#96]
Some climo operations with zppy fail (for example 200 year diurnal climo) because the command line arguments passed to ncclimo exceed the maximum length set by the OS.

@czender recommends an alternative way of passing input files:

```
srun -N 1 --time=30 --pty bash
caseid='20210625.v2rc3c-GWD.piControl.ne30pg2_EC30to60E2r2.chrysalis.eam.h4'
drc_in='/lcrc/group/e3sm/ac.golaz/E3SM_simulations/20210625.v2rc3c-GWD.piControl.ne30pg2_EC30to60E2r2.chrysalis/archive/atm/hist'
drc_out=${DATA}/ne30/clm
drc_rgr=${DATA}/ne30/rgr
yr_srt=801
yr_end=1000
cd ${drc_in};ls ${caseid}.0[89]??-*.nc ${caseid}.1000-*-*.nc > ~/input.txt
cd ${drc_in};ncclimo --dbg=1 --parallel=bck --climatology_mode=hfc --case=${caseid} --vars=PRECT --yr_srt=${yr_srt} --yr_end=${yr_end} --map=${DATA}/maps/map_ne30pg2_to_cmip6_180x360_aave.20200201.nc --output=${drc_out} --regrid=${drc_rgr} < ~/input.txt > ~/ncclimo.out 2>&1 & 
```

The key is to create a file containing a list of input files (`input.txt`) then feed that list as stdin (`< ~/input.txt`) to `ncclimo`. Very clever.

We need to modify climo.bash (diurnal section), as well as ts.bash which could have the same issue.

**Comment by golaz** [comment]
The least intrusive option might simply be to change the following:

https://github.com/E3SM-Project/zppy/blob/8bebca7ecc64f1af28c366cd8ba7c1031c248582/zppy/templates/climo.bash#L86-L107

Before ncclimo 

https://github.com/E3SM-Project/zppy/blob/8bebca7ecc64f1af28c366cd8ba7c1031c248582/zppy/templates/climo.bash#L86

`ls {{ case }}.{{ input_files }}.????-*.nc > input.txt`

Replace the last line of ncclimo command line arguments

https://github.com/E3SM-Project/zppy/blob/8bebca7ecc64f1af28c366cd8ba7c1031c248582/zppy/templates/climo.bash#L107) 

with:

`< input.txt`

**Comment by xylar** [comment]
@golaz, is this also affecting MPAS-Analysis?

**Comment by golaz** [comment]
@xylar: I have never seen such a problem with MPAS-Analysis, but I never tried to generate climatologies longer than 50 years.

**Comment by xylar** [comment]
@golaz, okay, I will address this if an when it arises.  Thanks!

**Comment by czender** [comment]
@xylar the problems @golaz encountered seemed to begin when the command line size reached ~100-200 kB, due to a combination of a large number (1200-2400) of files each with a longish name.
